{
  "hash": "aca20d4f51c5b5d342e233e4ad829813",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Climate resilience requires equitable access to quality green energy jobs. The City of Saint Paul is at the forefront.\nauthor:\n  - name: Elham Ali\n    corresponding: true\n    email: elham.ali@georgetown.edu\n    roles:\n      - Researcher\n      - Data Storytelling\n      - Human-centered Design\n      - Data Visualization\n    affiliations:\n      - Beeck Center for Social Impact and Innovation at Georgetown University\nlicense: CC BY-SA 4.0\nkeywords:\n  - climate justice\n  - climate-ready workforce\n  - green jobs\n  - climate change\n  - equity\ndate: '2024-09-19'\nabstract: |\n  Minnesota, particularly the City of Saint Paul, has seen a surge in climate resilience funding aimed at expanding green energy job opportunities. However, BIPOC communities remain underrepresented in these jobs and disproportionately suffer from the adverse effects of human-driven climate change.\nkeypoints:\n  - climate change\n  - green jobs\n  - workforce hiring\ncitation:\n  container-title: Beeck Center for Social Impact and Innovation\ndraft: false\nbibliography: references.bib\ncode-fold: true\n# reference-location: margin\n# citation-location: margin\necho: true\nwarning: false\n---\n\n\n\n\n\n## Background\n\nThis analysis looks at access to green energy jobs (like energy efficiency, renewable energy, and green construction) by race/ethnicity, gender, education, and income in St. Paul, Minnesota, USA.\n\n## Questions\n\nHere are some of the questions I will explore using different datasets:\n\n-   How much climate resilience funding has St. Paul received?\n-   What specific green jobs are being created in St. Paul (e.g., energy efficiency, renewable energy, green construction)?\n-   What is the quality of these jobs? How much do they pay? What qualifications are needed (education and experience)?\n-   Who is getting these jobs, based on education, race/ethnicity, gender, and income levels?\n\n## Data Sources\n\nThe data for this project comes from:\n\n-   The National Center for O\\*NET Development\n-   2023 Occupational Employment and Wage Survey\n-   Urban Institute 11 elements of job quality: Clean Energy Job Quality and Education Data\n-   National and local demographic data from the 2022 American Community Survey Public Use Microdata Sample (ACS PUMS)\n-   US Census Bureau's 2023 QuickFacts tool\n-   Invest.gov\n-   Geocorr from the Missouri Census Data Center\n\nI will reduce each large dataset to focus only on questions related to green jobs and job quality. Please note that some datasets have already been pre-processed in Python with specific filters applied. You can find the original raw datasets in the data folder for reference.\n\n## Analysis\n\nI will look at each question one by one and clean the data as I go. Some datasets might need to be combined, so I will organize the data during the analysis before exploring the results.\n\n### Load packages and libraries\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## For folder structure\nlibrary(here)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nhere() starts at /Users/elhamali/Documents/Data Projects/climate-equity-workforce\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ezknitr)\n\n## For data import/cleaning\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(purrr)\nlibrary(rlang)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'rlang'\n\nThe following objects are masked from 'package:purrr':\n\n    %@%, flatten, flatten_chr, flatten_dbl, flatten_int, flatten_lgl,\n    flatten_raw, invoke, splice\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(forcats)\nlibrary(readxl)\n\n## For graphing\nlibrary(highcharter)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRegistered S3 method overwritten by 'quantmod':\n  method            from\n  as.zoo.data.frame zoo \n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(igraph)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'igraph'\n\nThe following object is masked from 'package:rlang':\n\n    is_named\n\nThe following objects are masked from 'package:lubridate':\n\n    %--%, union\n\nThe following objects are masked from 'package:dplyr':\n\n    as_data_frame, groups, union\n\nThe following objects are masked from 'package:purrr':\n\n    compose, simplify\n\nThe following object is masked from 'package:tidyr':\n\n    crossing\n\nThe following object is masked from 'package:tibble':\n\n    as_data_frame\n\nThe following objects are masked from 'package:stats':\n\n    decompose, spectrum\n\nThe following object is masked from 'package:base':\n\n    union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(RColorBrewer)\nlibrary(htmlwidgets)\nlibrary(gt)\n# library(viridis)\n```\n:::\n\n\n\n\n\n### 1. Climate Resilience Funding for St. Paul\n\n::: callout-note\n## RQ 1: How much climate resilience funding has the City of Saint Paul received?\n\nAs of June 2024, **Minnesota** received a total of \\$7,101,423,527 in funding for climate resilience, while **St. Paul** received \\$446,286,762. Specifically, as of January 2024, St. Paul has secured \\$433,028,012 from the Bipartisan Infrastructure Law (BIL) and \\$13,258,750 from the Inflation Reduction Act (IRA) for **climate resilience efforts.**\n\nSt. Paul's funding makes up **6.28%** of Minnesota's total climate resilience funding. Nearly **95% of St. Paul's funding i**s allocated to **transportation** **projects**, with clean energy, buildings, and manufacturing receiving **less than 2% of the total**. It's like filling up a swimming pool with water but using only a small 8 oz glass for clean energy, buildings, and manufacturing.\n\nAs of January 2024, St. Paul received **\\$8,337,843 from the BIL** and **\\$200,000 from the IRA** specifically for investments in clean energy, buildings, and manufacturing.\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Import data\nfunding <- read_csv(here(\"processed_data\", \"FundingSummary.csv\"))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: One or more parsing issues, call `problems()` on your data frame for details,\ne.g.:\n  dat <- vroom(...)\n  problems(dat)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 49535 Columns: 15\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (14): Agency Name, Bureau Name, Program Name, Category, Subcategory, Pro...\ndbl  (1): Unique ID\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsaveRDS(funding, here(\"processed_data\", \"funding.rds\"))\n\nfunding <- readRDS(here(\"processed_data\", \"funding.rds\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n### Convert the `Funding Amount` to numeric and handling commas in the values\n\nfunding <- funding %>%\n  mutate(`Funding Amount` = as.numeric(gsub(\",\", \"\", `Funding Amount`)))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: There was 1 warning in `mutate()`.\nℹ In argument: `Funding Amount = as.numeric(gsub(\",\", \"\", `Funding Amount`))`.\nCaused by warning:\n! NAs introduced by coercion\n```\n\n\n:::\n:::\n\n\n\n\n\n#### Filter for MN State and City of St. Paul\n\nFirst, I will filter the dataset by State: **Minnesota**, and then narrow it down further to focus on the **City of St. Paul** and the surrounding region. Please note that St. Paul is part of the **Minneapolis-St. Paul-Bloomington, MN-WI** region, so I'll ensure it's included within that larger metropolitan area.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Filter for Minnesota funding\nminnesota_funding <- funding %>%\n  filter(State == \"Minnesota\")\n\nsaveRDS(minnesota_funding, here(\"processed_data\", \"minnesota_funding.rds\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Further filter for St. Paul, considering variations in city names\nst_paul_funding <- minnesota_funding %>%\n  filter(str_detect(City, regex(\"Saint Paul|St. Paul|South St. Paul|Minneapolis--St. Paul|Minneapolis-St. Paul\", ignore_case = TRUE)))\n\nsaveRDS(st_paul_funding, here(\"processed_data\", \"st_paul_funding.rds\"))\n\n# glimpse(st_paul_funding)\n```\n:::\n\n\n\n\n\n#### Calculate funding for MN State and City of St. Paul\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Set options to avoid scientific notation\noptions(scipen = 999)\n\n# Load Minnesota and St. Paul data\nminnesota_funding <- readRDS(here(\"processed_data\", \"minnesota_funding.rds\"))\nst_paul_funding <- readRDS(here(\"processed_data\", \"st_paul_funding.rds\"))\n\n# Calculate total funding for Minnesota\ntotal_minnesota_funding <- minnesota_funding %>%\n  summarise(total_funding = sum(`Funding Amount`, na.rm = TRUE))\n\ncat(\"The total amount of funding Minnesota received for climate as of June 2024 is $\", \n    format(total_minnesota_funding$total_funding, big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe total amount of funding Minnesota received for climate as of June 2024 is $ 7,101,423,527 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Calculate total funding for St. Paul\ntotal_st_paul_funding <- st_paul_funding %>%\n  summarise(total_funding = sum(`Funding Amount`, na.rm = TRUE))\n\ncat(\"The total amount of funding St. Paul received for climate as of June 2024 is $\", \n    format(total_st_paul_funding$total_funding, big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe total amount of funding St. Paul received for climate as of June 2024 is $ 446,286,762 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Calculate total funds by funding source for St. Paul\nsource_st_paul_funding <- st_paul_funding %>%\n  group_by(`Funding Source`) %>%\n  summarise(total_funding = sum(`Funding Amount`, na.rm = TRUE))\n\n# Calculate specific totals for BIL and IRA\nbil_funding <- st_paul_funding %>%\n  filter(`Funding Source` == \"BIL\") %>%\n  summarise(total_bil = sum(`Funding Amount`, na.rm = TRUE))\n\nira_funding <- st_paul_funding %>%\n  filter(`Funding Source` == \"IRA\") %>%\n  summarise(total_ira = sum(`Funding Amount`, na.rm = TRUE))\n\n# Print specific funding from BIL and IRA\ncat(\"As of January 2024, St. Paul has been allocated $\", \n    format(bil_funding$total_bil, big.mark = \",\", scientific = FALSE), \n    \" from the Bipartisan Infrastructure Law (BIL) and $\", \n    format(ira_funding$total_ira, big.mark = \",\", scientific = FALSE), \n    \" from the Inflation Reduction Act (IRA).\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAs of January 2024, St. Paul has been allocated $ 433,028,012  from the Bipartisan Infrastructure Law (BIL) and $ 13,258,750  from the Inflation Reduction Act (IRA).\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Filter for the specific category 'Clean Energy, Buildings, and Manufacturing'\nst_paul_clean_energy_funding <- st_paul_funding %>%\n  filter(Category == \"Clean Energy, Buildings, and Manufacturing\")\n\n# Calculate total funds by funding source for the specific category\nsource_st_paul_clean_energy_funding <- st_paul_clean_energy_funding %>%\n  group_by(`Funding Source`) %>%\n  summarise(total_funding = sum(`Funding Amount`, na.rm = TRUE))\n\n# Calculate total funding across all sources for the specific category\ntotal_st_paul_clean_energy_funding <- st_paul_clean_energy_funding %>%\n  summarise(total_funding = sum(`Funding Amount`, na.rm = TRUE))\n\n# Calculate specific totals for BIL and IRA in the specific category\nbil_clean_energy_funding <- st_paul_clean_energy_funding %>%\n  filter(`Funding Source` == \"BIL\") %>%\n  summarise(total_bil = sum(`Funding Amount`, na.rm = TRUE))\n\nira_clean_energy_funding <- st_paul_clean_energy_funding %>%\n  filter(`Funding Source` == \"IRA\") %>%\n  summarise(total_ira = sum(`Funding Amount`, na.rm = TRUE))\n\n# Print the total amount of funding for the specific category\ncat(\"The total amount of funding St. Paul received for 'Clean Energy, Buildings, and Manufacturing' as of June 2024 is $\", \n    format(total_st_paul_clean_energy_funding$total_funding, big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe total amount of funding St. Paul received for 'Clean Energy, Buildings, and Manufacturing' as of June 2024 is $ 8,537,843 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Print specific funding from BIL and IRA for the specific category\ncat(\"As of January 2024, St. Paul has been allocated $\", \n    format(bil_clean_energy_funding$total_bil, big.mark = \",\", scientific = FALSE), \n    \" from the Bipartisan Infrastructure Law (BIL) and $\", \n    format(ira_clean_energy_funding$total_ira, big.mark = \",\", scientific = FALSE), \n    \" from the Inflation Reduction Act (IRA) to invest in 'Clean Energy, Buildings, and Manufacturing'.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAs of January 2024, St. Paul has been allocated $ 8,337,843  from the Bipartisan Infrastructure Law (BIL) and $ 200,000  from the Inflation Reduction Act (IRA) to invest in 'Clean Energy, Buildings, and Manufacturing'.\n```\n\n\n:::\n:::\n\n\n\n\n\nAs of January 2024, St. Paul has been allocated \\$ 433,028,012 million from the Bipartisan Infrastructure Law (BIL) and \\$ 13,258,750 from the Inflation Reduction Act (IRA) to invest in climate resilience efforts in total.\n\nAs of January 2024, St. Paul has been allocated \\$ 8,337,843 million from the Bipartisan Infrastructure Law (BIL) and \\$ 200,000 from the Inflation Reduction Act (IRA) to invest in 'Clean Energy, Buildings, and Manufacturing'.\n\n#### Calculate fraction of St. Paul's funding from MN's\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nminnesota_funding <- readRDS(here(\"processed_data\", \"minnesota_funding.rds\"))\nst_paul_funding <- readRDS(here(\"processed_data\", \"st_paul_funding.rds\"))\n\n# Calculate total funding for Minnesota\ntotal_minnesota_funding <- minnesota_funding %>%\n  summarise(total_funding = sum(`Funding Amount`, na.rm = TRUE)) %>%\n  pull(total_funding)\n\n# Calculate total funding for St. Paul\ntotal_st_paul_funding <- st_paul_funding %>%\n  summarise(total_funding = sum(`Funding Amount`, na.rm = TRUE)) %>%\n  pull(total_funding)\n\n# Calculate the fraction of St. Paul's funding from Minnesota's total funding\nfraction_st_paul <- total_st_paul_funding / total_minnesota_funding\n\n# Output the results\ncat(\"The fraction of St. Paul's funding from Minnesota's total funding is: \", \n    round(fraction_st_paul, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe fraction of St. Paul's funding from Minnesota's total funding is:  0.0628 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"This means St. Paul's funding is\", round(fraction_st_paul * 100, 2), \"% of Minnesota's total funding.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThis means St. Paul's funding is 6.28 % of Minnesota's total funding.\n```\n\n\n:::\n:::\n\n\n\n\n\n#### Visualize categories of funding for St. Paul\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Group the St. Paul data by Category and calculate the total funding for each category\nst_paul_category_funding <- st_paul_funding %>%\n  group_by(Category) %>%\n  summarise(total_funding = sum(`Funding Amount`, na.rm = TRUE)) %>%\n  arrange(desc(total_funding))\n\ncolors <- brewer.pal(n = length(unique(st_paul_category_funding$Category)), \"Set3\")\n\n# Create an interactive bar chart using highcharter\nhchart_bar <- highchart() %>%\n  hc_chart(type = \"bar\") %>%\n  hc_xAxis(categories = st_paul_category_funding$Category, title = list(text = \"Category\")) %>%\n  hc_yAxis(title = list(text = \"Total Funding ($)\"), labels = list(format = \"{value:,.0f}\")) %>%\n  hc_add_series(name = \"Total Funding\", \n                data = st_paul_category_funding$total_funding, \n                colorByPoint = TRUE, \n                colors = colors) %>%\n  hc_title(text = \"Total Funding by Category in St. Paul\") %>%\n  hc_tooltip(pointFormat = \"Total Funding: ${point.y:,.0f}\") %>%\n  hc_exporting(\n    enabled = TRUE,\n    buttons = list(contextButton = list(menuItems = c(\"downloadPNG\", \"downloadJPEG\", \"downloadSVG\", \"downloadPDF\")))\n  )\n\n# Saving the chart as an HTML file\nsaveWidget(hchart_bar, file = here(\"graphs\", \"st_paul_funding_bar.html\"))\n```\n:::\n\n\n\n\n\nA quick glance tells us that almost **95%** of St. Paul's funding goes to transportation efforts. Clean energy, buildings and manufacturing received less than **2%** of funding.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Create an interactive pie chart using highcharter\nhchart_pie <- highchart() %>%\n  hc_chart(type = \"pie\") %>%\n  hc_add_series(name = \"Total Funding\", \n                data = list_parse2(st_paul_category_funding %>% \n                                   mutate(name = Category, y = total_funding)), \n                colors = colors) %>%\n  hc_title(text = \"Total Funding by Category in St. Paul\") %>%\n  hc_tooltip(pointFormat = \"Total Funding: ${point.y:,.0f}\") %>%\n  hc_plotOptions(pie = list(innerSize = '50%', dataLabels = list(enabled = TRUE))) %>%\n  hc_exporting(\n    enabled = TRUE,\n    buttons = list(contextButton = list(menuItems = c(\"downloadPNG\", \"downloadJPEG\", \"downloadSVG\", \"downloadPDF\")))\n  )\n\nsaveWidget(hchart_pie, file = here(\"graphs\", \"st_paul_funding_pie.html\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n## Export the funding data to CSV for graphing\nwrite.csv(minnesota_funding, here(\"processed_data\", \"minnesota_funding.csv\"), row.names = FALSE)\nwrite.csv(st_paul_funding, here(\"processed_data\", \"st_paul_funding.csv\"), row.names = FALSE)\n```\n:::\n\n\n\n\n\n### 2. Types of Green Jobs in St. Paul\n\n::: callout-note\n## RQ 2: What specific green jobs are being created in the Minneapolis-Saint Paul metropolitan area and nationally (e.g., energy efficiency, renewable energy, green construction)?\n\n[Nationally]{.underline}\n\nThere's a total of **17,119,730 employed people** in green jobs nationally. Specifically, in **Energy Efficiency**, there are 4,928,520 (28.79 %), in **Green Construction** there are 10,624,140 (62.06 %), and in **Renewable Energy Generation** there are 1,567,070 (9.15 %).\n\nThe **mean annual wage** for the occupation in U.S. dollars for green jobs is \\$78,363.4, and for non-green jobs is \\$73,763.67. That means green jobs pay **\\$4,599.73 more** than non-green jobs **nationally**.\n\nThe **mean hourly wage** for the occupation in U.S. dollars for green jobs is \\$37.67547, and for non-green jobs is \\$34.80. That means green jobs pay **\\$2.88 more** than non-green jobs **nationally**.\n\n[Minneapolis-Saint Paul Metropolitan Area]{.underline}\n\nThere's a total of **214,340 employed people** in green jobs in the Minneapolis-Saint Paul metropolitan area. Specifically, in **Energy Efficiency**, there are 66,410 ( 30.98 %), in **Green Construction** there are 124,680 ( 58.17 %), and in **Renewable Energy Generation** there are 23,250 ( 10.85 %).\n\nThe **mean annual wage** for the occupation in U.S. dollars for green jobs **in this area** is \\$84,561.7, and for non-green jobs is \\$77,192.53. That means green jobs in Saint Paul pay \\$7,369.169 more than non-green jobs in this area.\n\nThe **mean hourly wage** for the occupation in U.S. dollars for green jobs **in this area** is \\$40.65, and for non-green jobs is \\$36.31. That means green jobs in Saint Paul pay **\\$4.35 more** than non-green jobs in this area.\n:::\n\n#### Green jobs nationally\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Import national jobs data\nnational_jobs <- read_csv(here(\"processed_data\", \"OWES_and_ONET-National.csv\"))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 1420 Columns: 34\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (21): AREA_TITLE, PRIM_STATE, NAICS_TITLE, I_GROUP, OCC_CODE, OCC_TITLE,...\ndbl  (7): AREA, AREA_TYPE, NAICS, OWN_CODE, TOT_EMP, EMP_PRSE, MEAN_PRSE\nlgl  (6): JOBS_1000, LOC_QUOTIENT, PCT_TOTAL, PCT_RPT, ANNUAL, HOURLY\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsaveRDS(national_jobs, here(\"processed_data\", \"national_jobs.rds\"))\n\nnational_jobs  <- readRDS(here(\"processed_data\", \"national_jobs.rds\"))\n```\n:::\n\n\n\n\n\nHere, we'd want to filter to only green jobs\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Convert necessary columns to numeric where needed\nnational_jobs <- national_jobs %>%\n  mutate(\n    TOT_EMP = as.numeric(TOT_EMP),\n    # JOBS_1000 = as.numeric(JOBS_1000),\n    # PCT_TOTAL = as.numeric(PCT_TOTAL),\n    H_MEAN = as.numeric(H_MEAN),\n    A_MEAN = as.numeric(A_MEAN),\n    A_MEDIAN = as.numeric(A_MEDIAN),\n    H_MEDIAN = as.numeric(H_MEDIAN)\n  )\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: There were 4 warnings in `mutate()`.\nThe first warning was:\nℹ In argument: `H_MEAN = as.numeric(H_MEAN)`.\nCaused by warning:\n! NAs introduced by coercion\nℹ Run `dplyr::last_dplyr_warnings()` to see the 3 remaining warnings.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Filter the dataset to include only relevant sectors\nfiltered_jobs <- national_jobs %>%\n  filter(`O*NET-SOC Sector` %in% c(\"Energy Efficiency\", \"Renewable Energy Generation\", \"Green Construction\"))\n\n# Function to summarize data for each sector\nsummarize_by_sector <- function(df) {\n  df %>%\n    summarize(\n      TOT_EMP = sum(TOT_EMP, na.rm = TRUE),\n      # JOBS_1000 = sum(JOBS_1000 * TOT_EMP, na.rm = TRUE) / sum(TOT_EMP, na.rm = TRUE),\n      # PCT_TOTAL = sum(PCT_TOTAL * TOT_EMP, na.rm = TRUE) / sum(TOT_EMP, na.rm = TRUE),\n      H_MEAN = mean(H_MEAN, na.rm = TRUE),\n      A_MEAN = mean(A_MEAN, na.rm = TRUE),\n      A_MEDIAN = median(A_MEDIAN, na.rm = TRUE),\n      H_MEDIAN = median(H_MEDIAN, na.rm = TRUE)\n    )\n}\n\n# Summarize the data for each sector and overall\nsector_summary <- filtered_jobs %>%\n  group_by(`O*NET-SOC Sector`) %>%\n  summarize_by_sector()\n\n# Calculate the summary for all sectors combined\noverall_summary <- filtered_jobs %>%\n  summarize_by_sector()\n\n# Combine the results: sector-wise and overall\nfinal_summary <- bind_rows(sector_summary, tibble(`O*NET-SOC Sector` = \"All\", overall_summary))\n\n# Save the final summary as an RDS file and CSV for future reference\nsaveRDS(final_summary, here(\"processed_data\", \"sector_summary.rds\"))\nwrite_csv(final_summary, here(\"processed_data\", \"sector_summary.csv\"))\n\n# Output the final summary to the user\nprint(final_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  `O*NET-SOC Sector`           TOT_EMP H_MEAN A_MEAN A_MEDIAN H_MEDIAN\n  <chr>                          <dbl>  <dbl>  <dbl>    <dbl>    <dbl>\n1 Energy Efficiency            4928520   43.0 89371     86355     41.5\n2 Green Construction          10624140   33.9 70506.    60165     28.9\n3 Renewable Energy Generation  1567070   42.3 88028.    97010     46.6\n4 All                         17119730   37.7 78363.    67640     32.5\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Calculate total employment and sector percentages\ntotal_green_jobs <- final_summary %>% filter(`O*NET-SOC Sector` == \"All\") %>% pull(TOT_EMP)\n\nenergy_efficiency_jobs <- final_summary %>% filter(`O*NET-SOC Sector` == \"Energy Efficiency\") %>% pull(TOT_EMP)\ngreen_construction_jobs <- final_summary %>% filter(`O*NET-SOC Sector` == \"Green Construction\") %>% pull(TOT_EMP)\nrenewable_energy_jobs <- final_summary %>% filter(`O*NET-SOC Sector` == \"Renewable Energy Generation\") %>% pull(TOT_EMP)\n\n# Calculate the percentages\nenergy_efficiency_pct <- round((energy_efficiency_jobs / total_green_jobs) * 100, 2)\ngreen_construction_pct <- round((green_construction_jobs / total_green_jobs) * 100, 2)\nrenewable_energy_pct <- round((renewable_energy_jobs / total_green_jobs) * 100, 2)\n\n# Create the concatenated sentence\ncat(\"There's a total of\", format(total_green_jobs, big.mark = \",\", scientific = FALSE), \n    \"employed people in green jobs nationally. Specifically, in Energy Efficiency, there are\", \n    format(energy_efficiency_jobs, big.mark = \",\", scientific = FALSE), \n    \"(\", energy_efficiency_pct, \"%), in Green Construction there are\", \n    format(green_construction_jobs, big.mark = \",\", scientific = FALSE), \n    \"(\", green_construction_pct, \"%), and in Renewable Energy Generation there are\", \n    format(renewable_energy_jobs, big.mark = \",\", scientific = FALSE), \n    \"(\", renewable_energy_pct, \"%).\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThere's a total of 17,119,730 employed people in green jobs nationally. Specifically, in Energy Efficiency, there are 4,928,520 ( 28.79 %), in Green Construction there are 10,624,140 ( 62.06 %), and in Renewable Energy Generation there are 1,567,070 ( 9.15 %).\n```\n\n\n:::\n:::\n\n\n\n\n\nLet's visualize this so it's easier to compare across all green sectors\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Convert the O*NET-SOC Sector to a factor for ordering in the chart\nfinal_summary <- final_summary %>%\n  mutate(`O*NET-SOC Sector` = factor(`O*NET-SOC Sector`, levels = c(\"Energy Efficiency\", \"Green Construction\", \"Renewable Energy Generation\", \"All\")))\n\n# Visualizing TOT_EMP across the sectors\nhchart(final_summary, \"column\", hcaes(x = `O*NET-SOC Sector`, y = TOT_EMP)) %>%\n  hc_title(text = \"Total Employment by Sector\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Total Employment\"), labels = list(format = \"{value:,0f}\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:,0f}</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-13-1.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualizing H_MEAN (Mean Hourly Wage) across the sectors\nhchart(final_summary, \"column\", hcaes(x = `O*NET-SOC Sector`, y = H_MEAN)) %>%\n  hc_title(text = \"Mean Hourly Wage by Sector\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Mean Hourly Wage (USD)\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:.2f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-13-2.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualizing A_MEAN (Mean Annual Wage) across the sectors\nhchart(final_summary, \"column\", hcaes(x = `O*NET-SOC Sector`, y = A_MEAN)) %>%\n  hc_title(text = \"Mean Annual Wage by Sector\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Mean Annual Wage (USD)\"), labels = list(format = \"{value:,0f}\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:,0f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-13-3.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualizing A_MEDIAN (Median Annual Wage) across the sectors\nhchart(final_summary, \"column\", hcaes(x = `O*NET-SOC Sector`, y = A_MEDIAN)) %>%\n  hc_title(text = \"Median Annual Wage by Sector\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Median Annual Wage (USD)\"), labels = list(format = \"{value:,0f}\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:,0f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-13-4.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualizing H_MEDIAN (Median Hourly Wage) across the sectors\nhchart(final_summary, \"column\", hcaes(x = `O*NET-SOC Sector`, y = H_MEDIAN)) %>%\n  hc_title(text = \"Median Hourly Wage by Sector\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Median Hourly Wage (USD)\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:.2f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-13-5.png)\n:::\n:::\n\n\n\n\n\nI'm also curious about the differences between green jobs and non-green jobs for mean hourly wage and mean annual wage.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Define green jobs as sectors related to energy and construction\ngreen_jobs_sectors <- c(\"Energy Efficiency\", \"Renewable Energy Generation\", \"Green Construction\")\n\n# Add a new column to identify green and non-green jobs\nnational_jobs <- national_jobs %>%\n  mutate(\n    Job_Type = ifelse(`O*NET-SOC Sector` %in% green_jobs_sectors, \"Green Jobs\", \"Non-Green Jobs\")\n  )\n\n# Group by job type (Green vs Non-Green) and calculate mean wages\njob_type_summary <- national_jobs %>%\n  group_by(Job_Type) %>%\n  summarize(\n    H_MEAN = mean(H_MEAN, na.rm = TRUE),\n    A_MEAN = mean(A_MEAN, na.rm = TRUE)\n  )\n\n# Visualizing Mean Hourly Wage (H_MEAN) for Green vs Non-Green Jobs\nhchart(job_type_summary, \"column\", hcaes(x = Job_Type, y = H_MEAN)) %>%\n  hc_title(text = \"Mean Hourly Wage: Green Jobs vs Non-Green Jobs\") %>%\n  hc_xAxis(title = list(text = \"Job Type\")) %>%\n  hc_yAxis(title = list(text = \"Mean Hourly Wage (USD)\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:.2f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-14-1.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualizing Mean Annual Wage (A_MEAN) for Green vs Non-Green Jobs\nhchart(job_type_summary, \"column\", hcaes(x = Job_Type, y = A_MEAN)) %>%\n  hc_title(text = \"Mean Annual Wage: Green Jobs vs Non-Green Jobs\") %>%\n  hc_xAxis(title = list(text = \"Job Type\")) %>%\n  hc_yAxis(title = list(text = \"Mean Annual Wage (USD)\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:,0f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-14-2.png)\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Summarizing core findings nationally\n\n# Extract green and non-green job wage data\ngreen_wages <- job_type_summary %>% filter(Job_Type == \"Green Jobs\")\nnon_green_wages <- job_type_summary %>% filter(Job_Type == \"Non-Green Jobs\")\n\n# Calculate the difference between green and non-green jobs\ndifference_annual <- green_wages$A_MEAN - non_green_wages$A_MEAN\ndifference_hourly <- green_wages$H_MEAN - non_green_wages$H_MEAN\n\n# Format and print the sentences\ncat(\"The mean annual wage for the occupation in U.S. dollars for green jobs is $\", \n    format(green_wages$A_MEAN, big.mark = \",\", scientific = FALSE), \n    \", and for non-green jobs is $\", \n    format(non_green_wages$A_MEAN, big.mark = \",\", scientific = FALSE), \n    \". That means green jobs pay $\", \n    format(abs(difference_annual), big.mark = \",\", scientific = FALSE), \n    ifelse(difference_annual > 0, \" more\", \" less\"), \n    \" than non-green jobs nationally.\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe mean annual wage for the occupation in U.S. dollars for green jobs is $78,363.4, and for non-green jobs is $73,763.67. That means green jobs pay $4,599.726 more than non-green jobs nationally.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"The mean hourly wage for the occupation in U.S. dollars for green jobs is $\", \n    format(green_wages$H_MEAN, big.mark = \",\", scientific = FALSE), \n    \", and for non-green jobs is $\", \n    format(non_green_wages$H_MEAN, big.mark = \",\", scientific = FALSE), \n    \". That means green jobs pay $\", \n    format(abs(difference_hourly), big.mark = \",\", scientific = FALSE), \n    ifelse(difference_hourly > 0, \" more\", \" less\"), \n    \" than non-green jobs nationally.\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe mean hourly wage for the occupation in U.S. dollars for green jobs is $37.67547, and for non-green jobs is $34.79641. That means green jobs pay $2.879063 more than non-green jobs nationally.\n```\n\n\n:::\n:::\n\n\n\n\n\nI'd like to see a word cloud of different job titles for each sector\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Filter the dataset for green jobs only\ngreen_jobs <- national_jobs %>%\n  filter(`O*NET-SOC Sector` %in% c(\"Energy Efficiency\", \"Renewable Energy Generation\", \"Green Construction\"))\n\n# Extract job titles and count their occurrences\njob_titles <- green_jobs %>%\n  count(OCC_TITLE, sort = TRUE)\n\n# Create a word cloud using highcharter\nhchart(\n  job_titles, \n  \"wordcloud\", \n  hcaes(name = OCC_TITLE, weight = n)\n) %>%\n  hc_title(text = \"Word Cloud of Green Job Titles\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-16-1.png)\n:::\n:::\n\n\n\n\n\nNow let's create separate word clouds for each of the green sectors (\"Energy Efficiency\", \"Renewable Energy Generation\", and \"Green Construction\").\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Filter the dataset for each sector\nenergy_efficiency_jobs <- national_jobs %>%\n  filter(`O*NET-SOC Sector` == \"Energy Efficiency\")\n\nrenewable_energy_jobs <- national_jobs %>%\n  filter(`O*NET-SOC Sector` == \"Renewable Energy Generation\")\n\ngreen_construction_jobs <- national_jobs %>%\n  filter(`O*NET-SOC Sector` == \"Green Construction\")\n\n# Create a function to generate word clouds\ngenerate_wordcloud <- function(data, sector_name) {\n  job_titles <- data %>%\n    count(OCC_TITLE, sort = TRUE)\n  \n  hchart(\n    job_titles, \n    \"wordcloud\", \n    hcaes(name = OCC_TITLE, weight = n)\n  ) %>%\n    hc_title(text = paste(\"Word Cloud of\", sector_name, \"Job Titles\"))\n}\n\n# Generate word cloud for Energy Efficiency\nenergy_efficiency_wordcloud <- generate_wordcloud(energy_efficiency_jobs, \"Energy Efficiency\")\n\n# Generate word cloud for Renewable Energy Generation\nrenewable_energy_wordcloud <- generate_wordcloud(renewable_energy_jobs, \"Renewable Energy Generation\")\n\n# Generate word cloud for Green Construction\ngreen_construction_wordcloud <- generate_wordcloud(green_construction_jobs, \"Green Construction\")\n\n# Display the word clouds\nenergy_efficiency_wordcloud\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-17-1.png)\n:::\n\n```{.r .cell-code .hidden}\nrenewable_energy_wordcloud\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-17-2.png)\n:::\n\n```{.r .cell-code .hidden}\ngreen_construction_wordcloud\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-17-3.png)\n:::\n:::\n\n\n\n\n\nLet's export for graphing\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n## Export the national jobs data to CSV for graphing\nwrite.csv(national_jobs, here(\"processed_data\", \"national_jobs.csv\"), row.names = FALSE)\n\n# Export the job_type_summary dataset to CSV for graphing\nwrite.csv(job_type_summary, here(\"processed_data\", \"national_job_type_summary.csv\"), row.names = FALSE)\n```\n:::\n\n\n\n\n\n#### Green jobs in St. Paul\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Import St. Paul jobs data\nst_paul_jobs <- read_csv(here(\"processed_data\", \"OWES_and_ONET-St_Paul.csv\"))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 742 Columns: 34\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (26): AREA_TITLE, PRIM_STATE, NAICS_TITLE, I_GROUP, OCC_CODE, OCC_TITLE,...\ndbl  (4): AREA, AREA_TYPE, NAICS, OWN_CODE\nlgl  (4): PCT_TOTAL, PCT_RPT, ANNUAL, HOURLY\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsaveRDS(st_paul_jobs, here(\"processed_data\", \"st_paul_jobs.rds\"))\n\nst_paul_jobs <- readRDS(here(\"processed_data\", \"st_paul_jobs.rds\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Convert necessary columns to numeric where needed\nst_paul_jobs <- st_paul_jobs %>%\n  mutate(\n    TOT_EMP = as.numeric(TOT_EMP),\n    H_MEAN = as.numeric(H_MEAN),\n    A_MEAN = as.numeric(A_MEAN),\n    A_MEDIAN = as.numeric(A_MEDIAN),\n    H_MEDIAN = as.numeric(H_MEDIAN)\n  )\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: There were 5 warnings in `mutate()`.\nThe first warning was:\nℹ In argument: `TOT_EMP = as.numeric(TOT_EMP)`.\nCaused by warning:\n! NAs introduced by coercion\nℹ Run `dplyr::last_dplyr_warnings()` to see the 4 remaining warnings.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Filter the dataset to include only relevant green sectors\nfiltered_st_paul_jobs <- st_paul_jobs %>%\n  filter(`O*NET-SOC Sector` %in% c(\"Energy Efficiency\", \"Renewable Energy Generation\", \"Green Construction\"))\n\n# Function to summarize data for each sector\nsummarize_by_sector <- function(df) {\n  df %>%\n    summarize(\n      TOT_EMP = sum(TOT_EMP, na.rm = TRUE),\n      H_MEAN = mean(H_MEAN, na.rm = TRUE),\n      A_MEAN = mean(A_MEAN, na.rm = TRUE),\n      A_MEDIAN = median(A_MEDIAN, na.rm = TRUE),\n      H_MEDIAN = median(H_MEDIAN, na.rm = TRUE)\n    )\n}\n\n# Summarize the data for each sector and overall\nsector_summary_st_paul <- filtered_st_paul_jobs %>%\n  group_by(`O*NET-SOC Sector`) %>%\n  summarize_by_sector()\n\n# Calculate the summary for all sectors combined\noverall_summary_st_paul <- filtered_st_paul_jobs %>%\n  summarize_by_sector()\n\n# Combine the results: sector-wise and overall\nfinal_summary_st_paul <- bind_rows(sector_summary_st_paul, tibble(`O*NET-SOC Sector` = \"All\", overall_summary_st_paul))\n\n# Save the final summary as an RDS file and CSV for future reference\nsaveRDS(final_summary_st_paul, here(\"processed_data\", \"sector_summary_st_paul.rds\"))\nwrite_csv(final_summary_st_paul, here(\"processed_data\", \"sector_summary_st_paul.csv\"))\n\n# Output the final summary to the user\nprint(final_summary_st_paul)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  `O*NET-SOC Sector`          TOT_EMP H_MEAN A_MEAN A_MEDIAN H_MEDIAN\n  <chr>                         <dbl>  <dbl>  <dbl>    <dbl>    <dbl>\n1 Energy Efficiency             66410   45.5 94669.    98740     47.5\n2 Green Construction           124680   37.9 78809.    75800     36.4\n3 Renewable Energy Generation   23250   44.7 92991.    99690     47.9\n4 All                          214340   40.7 84562.    82170     39.5\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Calculate total employment and sector percentages for St. Paul\ntotal_green_jobs_st_paul <- final_summary_st_paul %>% filter(`O*NET-SOC Sector` == \"All\") %>% pull(TOT_EMP)\n\nenergy_efficiency_jobs_st_paul <- final_summary_st_paul %>% filter(`O*NET-SOC Sector` == \"Energy Efficiency\") %>% pull(TOT_EMP)\ngreen_construction_jobs_st_paul <- final_summary_st_paul %>% filter(`O*NET-SOC Sector` == \"Green Construction\") %>% pull(TOT_EMP)\nrenewable_energy_jobs_st_paul <- final_summary_st_paul %>% filter(`O*NET-SOC Sector` == \"Renewable Energy Generation\") %>% pull(TOT_EMP)\n\n# Calculate the percentages\nenergy_efficiency_pct_st_paul <- round((energy_efficiency_jobs_st_paul / total_green_jobs_st_paul) * 100, 2)\ngreen_construction_pct_st_paul <- round((green_construction_jobs_st_paul / total_green_jobs_st_paul) * 100, 2)\nrenewable_energy_pct_st_paul <- round((renewable_energy_jobs_st_paul / total_green_jobs_st_paul) * 100, 2)\n\n# Create the concatenated sentence for St. Paul\ncat(\"There's a total of\", format(total_green_jobs_st_paul, big.mark = \",\", scientific = FALSE), \n    \"employed people in green jobs in Saint Paul. Specifically, in Energy Efficiency, there are\", \n    format(energy_efficiency_jobs_st_paul, big.mark = \",\", scientific = FALSE), \n    \"(\", energy_efficiency_pct_st_paul, \"%), in Green Construction there are\", \n    format(green_construction_jobs_st_paul, big.mark = \",\", scientific = FALSE), \n    \"(\", green_construction_pct_st_paul, \"%), and in Renewable Energy Generation there are\", \n    format(renewable_energy_jobs_st_paul, big.mark = \",\", scientific = FALSE), \n    \"(\", renewable_energy_pct_st_paul, \"%).\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThere's a total of 214,340 employed people in green jobs in Saint Paul. Specifically, in Energy Efficiency, there are 66,410 ( 30.98 %), in Green Construction there are 124,680 ( 58.17 %), and in Renewable Energy Generation there are 23,250 ( 10.85 %).\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Visualizing TOT_EMP across the green sectors for St. Paul\nfinal_summary_st_paul <- final_summary_st_paul %>%\n  mutate(`O*NET-SOC Sector` = factor(`O*NET-SOC Sector`, levels = c(\"Energy Efficiency\", \"Green Construction\", \"Renewable Energy Generation\", \"All\")))\n\nhchart(final_summary_st_paul, \"column\", hcaes(x = `O*NET-SOC Sector`, y = TOT_EMP)) %>%\n  hc_title(text = \"Total Employment by Sector in Saint Paul\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Total Employment\"), labels = list(format = \"{value:,0f}\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:,0f}</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-20-1.png)\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Convert the O*NET-SOC Sector to a factor for ordering in the chart for St. Paul\nfinal_summary_st_paul <- final_summary_st_paul %>%\n  mutate(`O*NET-SOC Sector` = factor(`O*NET-SOC Sector`, levels = c(\"Energy Efficiency\", \"Green Construction\", \"Renewable Energy Generation\", \"All\")))\n\n# Visualizing TOT_EMP across the sectors for St. Paul\nhchart(final_summary_st_paul, \"column\", hcaes(x = `O*NET-SOC Sector`, y = TOT_EMP)) %>%\n  hc_title(text = \"Total Employment by Sector in Saint Paul\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Total Employment\"), labels = list(format = \"{value:,0f}\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:,0f}</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-21-1.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualizing H_MEAN (Mean Hourly Wage) across the sectors for St. Paul\nhchart(final_summary_st_paul, \"column\", hcaes(x = `O*NET-SOC Sector`, y = H_MEAN)) %>%\n  hc_title(text = \"Mean Hourly Wage by Sector in Saint Paul\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Mean Hourly Wage (USD)\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:.2f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-21-2.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualizing A_MEAN (Mean Annual Wage) across the sectors for St. Paul\nhchart(final_summary_st_paul, \"column\", hcaes(x = `O*NET-SOC Sector`, y = A_MEAN)) %>%\n  hc_title(text = \"Mean Annual Wage by Sector in Saint Paul\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Mean Annual Wage (USD)\"), labels = list(format = \"{value:,0f}\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:,0f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-21-3.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualizing A_MEDIAN (Median Annual Wage) across the sectors for St. Paul\nhchart(final_summary_st_paul, \"column\", hcaes(x = `O*NET-SOC Sector`, y = A_MEDIAN)) %>%\n  hc_title(text = \"Median Annual Wage by Sector in Saint Paul\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Median Annual Wage (USD)\"), labels = list(format = \"{value:,0f}\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:,0f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-21-4.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualizing H_MEDIAN (Median Hourly Wage) across the sectors for St. Paul\nhchart(final_summary_st_paul, \"column\", hcaes(x = `O*NET-SOC Sector`, y = H_MEDIAN)) %>%\n  hc_title(text = \"Median Hourly Wage by Sector in Saint Paul\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Median Hourly Wage (USD)\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:.2f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-21-5.png)\n:::\n\n```{.r .cell-code .hidden}\n# Define green jobs as sectors related to energy and construction for St. Paul\ngreen_jobs_sectors_st_paul <- c(\"Energy Efficiency\", \"Renewable Energy Generation\", \"Green Construction\")\n\n# Add a new column to identify green and non-green jobs for St. Paul\nst_paul_jobs <- st_paul_jobs %>%\n  mutate(\n    Job_Type = ifelse(`O*NET-SOC Sector` %in% green_jobs_sectors_st_paul, \"Green Jobs\", \"Non-Green Jobs\")\n  )\n\n# Group by job type (Green vs Non-Green) and calculate mean wages for St. Paul\njob_type_summary_st_paul <- st_paul_jobs %>%\n  group_by(Job_Type) %>%\n  summarize(\n    H_MEAN = mean(H_MEAN, na.rm = TRUE),\n    A_MEAN = mean(A_MEAN, na.rm = TRUE)\n  )\n\n# Visualizing Mean Hourly Wage (H_MEAN) for Green vs Non-Green Jobs in St. Paul\nhchart(job_type_summary_st_paul, \"column\", hcaes(x = Job_Type, y = H_MEAN)) %>%\n  hc_title(text = \"Mean Hourly Wage: Green Jobs vs Non-Green Jobs in Saint Paul\") %>%\n  hc_xAxis(title = list(text = \"Job Type\")) %>%\n  hc_yAxis(title = list(text = \"Mean Hourly Wage (USD)\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:.2f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-21-6.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualizing Mean Annual Wage (A_MEAN) for Green vs Non-Green Jobs in St. Paul\nhchart(job_type_summary_st_paul, \"column\", hcaes(x = Job_Type, y = A_MEAN)) %>%\n  hc_title(text = \"Mean Annual Wage: Green Jobs vs Non-Green Jobs in Saint Paul\") %>%\n  hc_xAxis(title = list(text = \"Job Type\")) %>%\n  hc_yAxis(title = list(text = \"Mean Annual Wage (USD)\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:,0f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-21-7.png)\n:::\n\n```{.r .cell-code .hidden}\n# Summarizing core findings for Saint Paul\n\n# Extract green and non-green job wage data for St. Paul\ngreen_wages_st_paul <- job_type_summary_st_paul %>% filter(Job_Type == \"Green Jobs\")\nnon_green_wages_st_paul <- job_type_summary_st_paul %>% filter(Job_Type == \"Non-Green Jobs\")\n\n# Calculate the difference between green and non-green jobs for St. Paul\ndifference_annual_st_paul <- green_wages_st_paul$A_MEAN - non_green_wages_st_paul$A_MEAN\ndifference_hourly_st_paul <- green_wages_st_paul$H_MEAN - non_green_wages_st_paul$H_MEAN\n\n# Format and print the sentences for Saint Paul\ncat(\"The mean annual wage for the occupation in U.S. dollars for green jobs in Saint Paul is $\", \n    format(green_wages_st_paul$A_MEAN, big.mark = \",\", scientific = FALSE), \n    \", and for non-green jobs is $\", \n    format(non_green_wages_st_paul$A_MEAN, big.mark = \",\", scientific = FALSE), \n    \". That means green jobs in Saint Paul pay $\", \n    format(abs(difference_annual_st_paul), big.mark = \",\", scientific = FALSE), \n    ifelse(difference_annual_st_paul > 0, \" more\", \" less\"), \n    \" than non-green jobs in Saint Paul.\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe mean annual wage for the occupation in U.S. dollars for green jobs in Saint Paul is $84,561.7, and for non-green jobs is $77,192.53. That means green jobs in Saint Paul pay $7,369.169 more than non-green jobs in Saint Paul.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"The mean hourly wage for the occupation in U.S. dollars for green jobs in Saint Paul is $\", \n    format(green_wages_st_paul$H_MEAN, big.mark = \",\", scientific = FALSE), \n    \", and for non-green jobs is $\", \n    format(non_green_wages_st_paul$H_MEAN, big.mark = \",\", scientific = FALSE), \n    \". That means green jobs in Saint Paul pay $\", \n    format(abs(difference_hourly_st_paul), big.mark = \",\", scientific = FALSE), \n    ifelse(difference_hourly_st_paul > 0, \" more\", \" less\"), \n    \" than non-green jobs in Saint Paul.\\n\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe mean hourly wage for the occupation in U.S. dollars for green jobs in Saint Paul is $40.65447, and for non-green jobs is $36.30688. That means green jobs in Saint Paul pay $4.347591 more than non-green jobs in Saint Paul.\n```\n\n\n:::\n:::\n\n\n\n\n\nI'd like to see a word cloud of different job titles for each sector in St. Paul\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Filter the dataset for green jobs only in St. Paul\ngreen_jobs_st_paul <- st_paul_jobs %>%\n  filter(`O*NET-SOC Sector` %in% c(\"Energy Efficiency\", \"Renewable Energy Generation\", \"Green Construction\"))\n\n# Extract job titles and count their occurrences in St. Paul\njob_titles_st_paul <- green_jobs_st_paul %>%\n  count(OCC_TITLE, sort = TRUE)\n\n# Create a word cloud for green jobs in St. Paul using highcharter\nhchart(\n  job_titles_st_paul, \n  \"wordcloud\", \n  hcaes(name = OCC_TITLE, weight = n)\n) %>%\n  hc_title(text = \"Word Cloud of Green Job Titles in Saint Paul\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-22-1.png)\n:::\n:::\n\n\n\n\n\nNow let's create separate word clouds for each of the green sectors (\"Energy Efficiency\", \"Renewable Energy Generation\", and \"Green Construction\") for St. Paul\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Filter the dataset for each sector in St. Paul\nenergy_efficiency_jobs_st_paul <- st_paul_jobs %>%\n  filter(`O*NET-SOC Sector` == \"Energy Efficiency\")\n\nrenewable_energy_jobs_st_paul <- st_paul_jobs %>%\n  filter(`O*NET-SOC Sector` == \"Renewable Energy Generation\")\n\ngreen_construction_jobs_st_paul <- st_paul_jobs %>%\n  filter(`O*NET-SOC Sector` == \"Green Construction\")\n\n# Create a function to generate word clouds for St. Paul sectors\ngenerate_wordcloud_st_paul <- function(data, sector_name) {\n  job_titles <- data %>%\n    count(OCC_TITLE, sort = TRUE)\n  \n  hchart(\n    job_titles, \n    \"wordcloud\", \n    hcaes(name = OCC_TITLE, weight = n)\n  ) %>%\n    hc_title(text = paste(\"Word Cloud of\", sector_name, \"Job Titles in Saint Paul\"))\n}\n\n# Generate word cloud for Energy Efficiency in St. Paul\nenergy_efficiency_wordcloud_st_paul <- generate_wordcloud_st_paul(energy_efficiency_jobs_st_paul, \"Energy Efficiency\")\n\n# Generate word cloud for Renewable Energy Generation in St. Paul\nrenewable_energy_wordcloud_st_paul <- generate_wordcloud_st_paul(renewable_energy_jobs_st_paul, \"Renewable Energy Generation\")\n\n# Generate word cloud for Green Construction in St. Paul\ngreen_construction_wordcloud_st_paul <- generate_wordcloud_st_paul(green_construction_jobs_st_paul, \"Green Construction\")\n\n# Display the word clouds for St. Paul\nenergy_efficiency_wordcloud_st_paul\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-23-1.png)\n:::\n\n```{.r .cell-code .hidden}\nrenewable_energy_wordcloud_st_paul\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-23-2.png)\n:::\n\n```{.r .cell-code .hidden}\ngreen_construction_wordcloud_st_paul\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-23-3.png)\n:::\n:::\n\n\n\n\n\nLet's export for graphing\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Export the St. Paul jobs data to CSV for graphing\nwrite.csv(st_paul_jobs, here(\"processed_data\", \"st_paul_jobs.csv\"), row.names = FALSE)\n\n# Export the job_type_summary dataset for St. Paul to CSV for graphing\nwrite.csv(job_type_summary_st_paul, here(\"processed_data\", \"st_paul_job_type_summary.csv\"), row.names = FALSE)\n```\n:::\n\n\n\n\n\n### 3. Quality, Pay, and Qualifications of Green Jobs\n\n::: callout-note\n## RQ 3: What is the quality of these green jobs? How much do they pay? What qualifications are needed (education and experience) nationally?\n\n**Higher education** is associated with better-quality green jobs, particularly in the energy efficiency sector. Most high- and medium-quality jobs in energy efficiency require at least a Bachelor's Degree.\n\n**Individuals with lower education levels** are more likely to end up in green construction, especially in lower-quality jobs. Energy efficiency tends to offer a better quality of jobs across all education levels, with strong representation in both high and medium-quality segments.\n\n**Union membership** is **associated** with **higher-quality jobs** in all three sectors, particularly in energy efficiency and renewable energy generation, where a majority of high-quality jobs are unionized.\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Import green job quality data\nquality_green_jobs <- read_csv(here(\"processed_data\", \"Job_Info_Merged_All_Green.csv\"))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 128 Columns: 29\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (14): Reported Occupation, O*NET-SOC Code, O*NET-SOC Title, O*NET-SOC Ca...\ndbl (15): Renewable Energy Generation, Energy Efficiency, Green Construction...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsaveRDS(quality_green_jobs, here(\"processed_data\", \"quality_green_jobs.rds\"))\n\nquality_green_jobs <- readRDS(here(\"processed_data\", \"quality_green_jobs.rds\"))\n```\n:::\n\n\n\n\n\nNow, let's transform this dataframe so it's visualization-ready.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Rename columns to snake_case format\nquality_green_jobs <- quality_green_jobs %>%\n  rename(\n    report_occupation = `Reported Occupation`,\n    onet_soc_code = `O*NET-SOC Code`,\n    onet_soc_title = `O*NET-SOC Title`,\n    onet_soc_category = `O*NET-SOC Category`,\n    onet_soc_sector = `O*NET-SOC Sector`,\n    renewable_energy_generation = `Renewable Energy Generation`,\n    energy_efficiency = `Energy Efficiency`,\n    green_construction = `Green Construction`,\n    benchmark_total = `Benchmark Total`,\n    wage = Wage,\n    forty_hours = `40 hours`,\n    schedule = Schedule,\n    health_ins = `Health Ins`,\n    retirement = Retirement,\n    growth = Growth,\n    unemployment = Unemployment,\n    illness_injury = `Illness/injury`,\n    ojt = OJT,\n    union = Union,\n    autonomy_benchmark = autonomy_benchmark,\n    quality = quality,\n    education = education,\n    matrix_title = `2022 National Employment Matrix title`,\n    matrix_code = `2022 National Employment Matrix code`,\n    typical_education_needed = `Typical education needed for entry`,\n    work_experience_related = `Work experience in a related occupation`,\n    on_the_job_training = `Typical on-the-job training needed to attain competency in the occupation`\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Convert the variables to the correct types\nquality_green_jobs <- quality_green_jobs %>%\n  mutate(\n    # Factors\n    onet_soc_category = factor(onet_soc_category),\n    onet_soc_sector = factor(onet_soc_sector),\n    quality = factor(quality, levels = c(\"Low Quality\", \"Medium Quality\", \"High Quality\")),\n    education = factor(education),\n    typical_education_needed = factor(typical_education_needed),\n    work_experience_related = factor(work_experience_related),\n    on_the_job_training = factor(on_the_job_training),\n    \n    # Yes/No columns as numeric (1 for Yes, 0 for No)\n    renewable_energy_generation = as.numeric(renewable_energy_generation),\n    energy_efficiency = as.numeric(energy_efficiency),\n    green_construction = as.numeric(green_construction),\n    wage = as.numeric(wage),\n    forty_hours = as.numeric(forty_hours),\n    schedule = as.numeric(schedule),\n    health_ins = as.numeric(health_ins),\n    retirement = as.numeric(retirement),\n    growth = as.numeric(growth),\n    unemployment = as.numeric(unemployment),\n    illness_injury = as.numeric(illness_injury),\n    ojt = as.numeric(ojt),\n    union = as.numeric(union),\n    autonomy_benchmark = as.numeric(autonomy_benchmark)\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Visualize quality jobs compared across sectors\nquality_summary <- quality_green_jobs %>%\n  gather(key = \"sector\", value = \"is_green_job\", renewable_energy_generation, energy_efficiency, green_construction) %>%\n  filter(is_green_job == 1) %>%\n  group_by(sector, quality) %>%\n  summarise(count = n()) %>%\n  mutate(percentage = count / sum(count) * 100)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`summarise()` has grouped output by 'sector'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nggplot(quality_summary, aes(x = sector, y = percentage, fill = quality)) +\n  geom_bar(stat = \"identity\", position = \"fill\", width = 0.7) +\n  geom_text(aes(label = paste0(round(percentage, 1), \"%\")), \n            position = position_fill(vjust = 0.5), size = 4) +\n  labs(x = \"Sector\", y = \"Percentage\", title = \"Green Job Quality by Sector\") +\n  scale_fill_manual(values = c(\"High Quality\" = \"#1f77b4\", \"Medium Quality\" = \"#ffbb78\", \"Low Quality\" = \"#2ca02c\")) +\n  theme_minimal() +\n  theme(legend.title = element_blank())\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-28-1.png)\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Visualize quality jobs compared for sector, education, and quality\nquality_summary_education <- quality_green_jobs %>%\n  gather(key = \"sector\", value = \"is_green_job\", renewable_energy_generation, energy_efficiency, green_construction) %>%\n  filter(is_green_job == 1) %>%\n  group_by(sector, quality, education) %>%\n  summarise(count = n()) %>%\n  mutate(percentage = count / sum(count) * 100)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`summarise()` has grouped output by 'sector', 'quality'. You can override using\nthe `.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nggplot(quality_summary_education, aes(x = education, y = percentage, fill = sector)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  facet_wrap(~ quality, ncol = 1, scales = \"free_y\") + # Separate the quality levels\n  geom_text(aes(label = paste0(round(percentage, 1), \"%\")), \n            position = position_dodge(width = 0.9), vjust = -0.5, size = 3) +\n  labs(x = \"Education Level\", y = \"Percentage\", title = \"Green Job Quality by Sector and Education\") +\n  theme_minimal() +\n  theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-29-1.png)\n:::\n:::\n\n\n\n\n\nThis graph shows how the distribution of green jobs (energy efficiency, green construction, renewable energy generation) varies across different levels of education, segmented by job quality (Low, Medium, High quality).\n\nBased on the above graph:\n\n-   **Energy Efficiency** consistently dominates high-quality and medium-quality green jobs across most education levels, suggesting that this sector offers the most secure and rewarding jobs for those with varying levels of education.\n\n-   **Green Construction** has a significant presence in low-quality and medium-quality jobs, especially for those with lower education levels (such as high school diplomas or no formal educational credentials).\n\n-   **Renewable Energy Generation** seems to have fewer high-quality job opportunities compared to energy efficiency, but it does offer medium-quality opportunities, particularly for those with lower education levels.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# # Matrix table that shows green job quality segmented by variables from wage to union across the three sectors (renewable_energy_generation, energy_efficiency, green_construction)\n\n# # Transform the data to long format\n# long_quality_jobs <- quality_green_jobs %>%\n#   gather(key = \"sector\", value = \"is_green_job\", renewable_energy_generation, energy_efficiency, green_construction) %>%\n#   filter(is_green_job == 1) %>%\n#   select(sector, quality, wage, forty_hours, schedule, health_ins, retirement, growth, unemployment, illness_injury, ojt, union, autonomy_benchmark) %>%\n#   pivot_longer(cols = wage:autonomy_benchmark, names_to = \"variable\", values_to = \"value\") %>%\n#   group_by(sector, quality, variable) %>%\n#   summarise(proportion = mean(value)) %>%\n#   ungroup() %>%\n#   arrange(sector, quality, variable)\n# \n# # Generate matrix table using gt\n# matrix_table <- long_quality_jobs %>%\n#   pivot_wider(names_from = quality, values_from = proportion) %>%\n#   gt() %>%\n#   tab_header(\n#     title = \"Green Job Quality Matrix by Sector and Variables\",\n#     subtitle = \"Proportion of Each Job Quality Level Across Wage, Hours, Benefits, etc.\"\n#   ) %>%\n#   fmt_number(\n#     columns = vars(`High Quality`, `Medium Quality`, `Low Quality`),\n#     decimals = 2\n#   )\n# \n# # Display the matrix table\n# print(matrix_table)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Visualize quality jobs compared for sector, union membership, and quality\nquality_summary_union <- quality_green_jobs %>%\n  gather(key = \"sector\", value = \"is_green_job\", renewable_energy_generation, energy_efficiency, green_construction) %>%\n  filter(is_green_job == 1) %>%\n  group_by(sector, quality, union) %>%\n  summarise(count = n()) %>%\n  mutate(percentage = count / sum(count) * 100)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`summarise()` has grouped output by 'sector', 'quality'. You can override using\nthe `.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nggplot(quality_summary_union, aes(x = as.factor(union), y = percentage, fill = sector)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  facet_wrap(~ quality, ncol = 1, scales = \"free_y\") + # Separate the quality levels\n  geom_text(aes(label = paste0(round(percentage, 1), \"%\")), \n            position = position_dodge(width = 0.9), vjust = -0.5, size = 3) +\n  labs(x = \"Union Membership\", y = \"Percentage\", title = \"Green Job Quality by Sector and Union Membership\") +\n  theme_minimal() +\n  theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-31-1.png)\n:::\n:::\n\n\n\n\n\nThe above graph shows green job quality segmented by union membership across three sectors: **Energy Efficiency**, **Green Construction**, and **Renewable Energy Generation**.\n\n-   **Union membership** is **associated** with **higher-quality jobs** in all three sectors, particularly in energy efficiency and renewable energy generation, where a majority of high-quality jobs are unionized. This suggests that **unions play a significant role in securing better working conditions and benefits** for workers in green jobs.\n\n-   **Medium-quality jobs** also show a clear advantage for unionized workers across the sectors, particularly in green construction and renewable energy generation.\n\n-   The presence of **union coverage even in low-quality jobs** across sectors might indicate that unionized jobs are spread across different quality categories, though the majority of benefits seem to concentrate in medium- and high-quality roles.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Export the green quality jobs data to CSV for graphing\nsaveRDS(quality_green_jobs, here(\"processed_data\", \"quality_green_jobs.rds\"))\n\nwrite_csv(quality_green_jobs, here(\"processed_data\", \"quality_green_jobs.csv\"))\n```\n:::\n\n\n\n\n\n### 4. Demographics of Green Job Recipients\n\n::: callout-note\n## RQ 4: Who is getting these green jobs, based on education, race/ethnicity, gender, and income levels in the City of Saint Paul?\n\nOf the more than **303,820 people** who live in **St. Paul**, **50.5%** are women, which is aligned with the national average. The majority of residents in St. Paul are **white** (54.3%). **Black or African American people** (15.6%) make up the largest community of color in the city. Other **communities of color,** including Asian (18.4%), Alaska and Native American (0.7%), Hispanic or Latino (8.6%) and Two or More Races (7.8%), make up about 41.5% of the population. Around **42.8% of people aged 25 and older have a bachelor's degree** in St. Paul, which is higher than the national rate of 34% but lower than Minneapolis' 54%.\n:::\n\nIn the following figures, we describe the challenges women and people of color in Saint Paul are likely to face in equitably accessing the jobs that may be created through BIL and IRA funding in three specific sectors: energy efficiency, renewable-energy generation, and green construction.\n\n-   **2023 Occupational Employment and Wage Survey (OEWS):**\n\n    -   Provides employment and wage data by occupation.\n\n    -   It's organized at the **Metropolitan Statistical Area (MSA)** level, which includes a broader geographic area (e.g., Minneapolis-St. Paul-Bloomington, MN-WI Metro).\n\n    -   This data gives insights into **jobs and wages** but lacks detailed individual demographics such as race, ethnicity, education, etc.\n\n-   **Geocorr Data from the Missouri Census Data Center:**\n\n    -   This data helps map geographic boundaries like PUMAs (Public Use Microdata Areas) to more specific local areas, such as St. Paul.\n\n    -   By using geographic weighting from Geocorr, we can estimate **St. Paul-specific** statistics from the broader MSA-level data in the OEWS.\n\n1.  Load and explore the two datasets.\n2.  Filter the OEWS data to the Minneapolis-St. Paul-Bloomington Metro area.\n3.  Get weights from the Geocorr file to adjust for St. Paul's population.\n4.  Merge demographic data (from ACS) with the estimated job/wage data from OEWS.\n5.  Analyze the final dataset for insights into who holds green jobs in St. Paul.\n\n**2023 Occupational Employment and Wage Survey**\n\n✅[National level data](https://docs.google.com/spreadsheets/d/1I2munGunOJgdI2iWRW7p0BVU0O13r4zb/edit?gid=1944656488#gid=1944656488)\n\n✅[Minneapolis-St. Paul-Bloomington, MN-WI](https://docs.google.com/spreadsheets/d/105RYiRn-1LIVC-iUdCD3fCKROfOGH_M62s45gbo7GFM/edit?gid=2141627594#gid=2141627594)\n\n**Geocorr from the Missouri Census Data Center**\n\n[Minnesota Level ](https://docs.google.com/spreadsheets/d/1wRr-jATTjaXpErUfSCAZsoSn-lt1-TZtWv_Hoq2C29Q/edit?gid=1877088889#gid=1877088889): Contains data mapping PUMAs to Metropolitan Statistical Areas and PUMAs to cities\n\n**Processed** \n\n[St. Paul - ACS PUMS - Five Years + O\\*NET Green Jobs](https://drive.google.com/file/d/1uyRoXlExkExjlJytEh8meqD3D--4Hwj4/view?usp=drive_link)\n\n[National - ACS PUMS - Five Years + O\\*NET Green Jobs](https://drive.google.com/file/d/1C3opSLifg144MIYnISHmf7wwZuAe2TQJ/view?usp=drive_link)\n\nWe will first need to load the **OEWS** data (Occupational Employment and Wage Survey) and the **Geocorr** data (geographic weights from the Missouri Census Data Center) into R.\n\n-   **OEWS:** processed_data/OWES_and_ONET_St_Paul\n\n-   **Geocorr:** raw_data/Geocorr from the Missouri Census Data Center - Minnesota.xlsx\n\nWe have the **ACS (American Community Survey)** data that provides demographic information (education, race, gender, income), so we'll load that as well.\n\n-   **ACS:** processed_data/St_Paul_ACS_All_Jobs.csv\n\n**Load the OEWS data** (Occupational Employment and Wage Survey), the Geocorr data (geographic weights from the Missouri Census Data Center), and the ACS (American Community Survey) data that provides demographic information (education, race, gender, income). The OEWS Data: is already filtered to the Minneapolis-St. Paul-Bloomington, MN-WI Metro Area.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Load St. Paul jobs data (OEWS dataset)\nst_paul_jobs <- read_csv(here(\"processed_data\", \"OWES_and_ONET-St_Paul.csv\"))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 742 Columns: 34\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (26): AREA_TITLE, PRIM_STATE, NAICS_TITLE, I_GROUP, OCC_CODE, OCC_TITLE,...\ndbl  (4): AREA, AREA_TYPE, NAICS, OWN_CODE\nlgl  (4): PCT_TOTAL, PCT_RPT, ANNUAL, HOURLY\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsaveRDS(st_paul_jobs, here(\"processed_data\", \"st_paul_jobs.rds\"))\nst_paul_jobs <- readRDS(here(\"processed_data\", \"st_paul_jobs.rds\"))\n\n# Load the Geocorr data from Excel (Minnesota-specific)\ngeocorr_data <- read_excel(here(\"raw_data\", \"Geocorr from the Missouri Census Data Center - Minnesota.xlsx\"))\n\n# Load the ACS data for St. Paul (demographic data)\nacs_data <- read_csv(here(\"processed_data\", \"St_Paul_ACS_All_Jobs.csv\"))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 1730 Columns: 19\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (7): RT, SERIALNO, SOCP, RAC1P, SEX, SCHL, O*NET-SOC Title\ndbl (12): DIVISION, SPORDER, PUMA20, REGION, ST, AGEP, PINCP, ADJINC, WAGP, ...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsaveRDS(acs_data, here(\"processed_data\", \"acs_data.rds\"))\nacs_data <- readRDS(here(\"processed_data\", \"acs_data.rds\"))\n```\n:::\n\n\n\n\n\n**Use Geocorr to apply weights.** The **Geocorr** data provides the geographic weights that represent the population of St. Paul relative to the larger metro area.The purpose of this step is to adjust the OEWS data to better represent **St. Paul** specifically. We will calculate the percentage of St. Paul's population in the larger metro area using **Geocorr** and apply this as a weight to the OEWS data.\n\nSince we are working with PUMAs (Public Use Microdata Areas) and need to adjust the OEWS data for St. Paul using the Geocorr weights, we'll focus on using:\n\n-   `Total population (2020 Census)` to understand the population of each PUMA.\n\n-   `puma22-to-cbsa20` allocation factor, which represents the proportion of the population in each PUMA that falls within the Minneapolis-St. Paul-Bloomington metro area.\n\nThe St. Paul weighted allocation factor is 1, which means that for these specific PUMAs (representing **Ramsey County--St. Paul City**), the entire population is considered part of the Minneapolis-St. Paul-Bloomington metro area. This result suggests that we can apply the full population of these PUMAs without needing further weighting, which simplifies the next steps.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Filter the Geocorr data to only include St. Paul PUMAs\nst_paul_geocorr <- geocorr_data %>%\n  filter(`PUMA22 name` %in% c(\n    \"Ramsey County--St. Paul City (Northwest)\", \n    \"Ramsey County--St. Paul City (Southwest)\", \n    \"Ramsey County--St. Paul City (East)\"\n  ))\n\n# Calculate the total population for St. Paul PUMAs and the weighted allocation factor\nst_paul_population <- sum(st_paul_geocorr$`Total population (2020 Census)`, na.rm = TRUE)\nmetro_population <- sum(geocorr_data$`Total population (2020 Census)`, na.rm = TRUE)\n\n# Calculate the weighted population factor for St. Paul within the metro area using the allocation factor\nst_paul_weight <- sum(st_paul_geocorr$`puma22-to-cbsa20 allocation factor`, na.rm = TRUE) / nrow(st_paul_geocorr)\n\n# Output the results\ncat(\"St. Paul weighted allocation factor:\", st_paul_weight, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSt. Paul weighted allocation factor: 1 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"St. Paul population:\", format(st_paul_population, big.mark = \",\", scientific = FALSE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSt. Paul population: 311,527 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"Metro area population:\", format(metro_population, big.mark = \",\", scientific = FALSE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMetro area population: 5,706,494 \n```\n\n\n:::\n:::\n\n\n\n\n\n**Estimate St. Paul-specific data**. Multiply the employment numbers and wages in the **OEWS** data by the St. Paul weight to get **St. Paul-specific** employment and wage estimates.\n\nWe'll multiply the employment numbers (TOT_EMP) and wages (H_MEAN and A_MEAN) from the **OEWS** dataset by this St. Paul weight to get **St. Paul-specific estimates**.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Ensure that the necessary columns are numeric\nst_paul_jobs <- st_paul_jobs %>%\n  mutate(\n    TOT_EMP = as.numeric(TOT_EMP),  # Convert total employment to numeric\n    H_MEAN = as.numeric(H_MEAN),    # Convert mean hourly wage to numeric\n    A_MEAN = as.numeric(A_MEAN)     # Convert mean annual wage to numeric\n  )\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: There were 3 warnings in `mutate()`.\nThe first warning was:\nℹ In argument: `TOT_EMP = as.numeric(TOT_EMP)`.\nCaused by warning:\n! NAs introduced by coercion\nℹ Run `dplyr::last_dplyr_warnings()` to see the 2 remaining warnings.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Apply the St. Paul weight to the OEWS dataset to adjust the employment and wage data for St. Paul\nst_paul_jobs_weighted <- st_paul_jobs %>%\n  mutate(\n    TOT_EMP_St_Paul = TOT_EMP * st_paul_weight,  # Adjusting total employment to St. Paul\n    H_MEAN_St_Paul = H_MEAN * st_paul_weight,    # Adjusting mean hourly wage\n    A_MEAN_St_Paul = A_MEAN * st_paul_weight     # Adjusting mean annual wage\n  )\n\n# Output a glimpse of the adjusted St. Paul-specific job data\nglimpse(st_paul_jobs_weighted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 742\nColumns: 37\n$ AREA               <dbl> 33460, 33460, 33460, 33460, 33460, 33460, 33460, 33…\n$ AREA_TITLE         <chr> \"Minneapolis-St. Paul-Bloomington, MN-WI\", \"Minneap…\n$ AREA_TYPE          <dbl> 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, …\n$ PRIM_STATE         <chr> \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN…\n$ NAICS              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ NAICS_TITLE        <chr> \"Cross-industry\", \"Cross-industry\", \"Cross-industry…\n$ I_GROUP            <chr> \"cross-industry\", \"cross-industry\", \"cross-industry…\n$ OWN_CODE           <dbl> 1235, 1235, 1235, 1235, 1235, 1235, 1235, 1235, 123…\n$ OCC_CODE           <chr> \"00-0000\", \"11-0000\", \"11-1011\", \"11-1021\", \"11-103…\n$ OCC_TITLE          <chr> \"All Occupations\", \"Management Occupations\", \"Chief…\n$ O_GROUP            <chr> \"total\", \"major\", \"detailed\", \"detailed\", \"detailed…\n$ TOT_EMP            <dbl> 1911030, 140870, 4420, 48300, 70, 90, 7000, 7390, 9…\n$ EMP_PRSE           <chr> \"0\", \"1.2\", \"3.9\", \"2\", \"11.9\", \"20.5\", \"3.4\", \"11.…\n$ JOBS_1000          <chr> \"1000\", \"73.712\", \"2.315\", \"25.272\", \"0.036\", \"0.04…\n$ LOC_QUOTIENT       <chr> \"1\", \"1.07\", \"1.66\", \"1.09\", \"0.17\", \"0.36\", \"1.51\"…\n$ PCT_TOTAL          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ PCT_RPT            <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ H_MEAN             <dbl> 33.80, 69.10, 129.79, 59.93, NA, 59.25, 86.25, 81.1…\n$ A_MEAN             <dbl> 70290, 143730, 269950, 124650, 82650, 123240, 17939…\n$ MEAN_PRSE          <chr> \"0.5\", \"1\", \"3.5\", \"1.2\", \"2.6\", \"8.7\", \"1.9\", \"2.4…\n$ H_PCT10            <chr> \"15.06\", \"29.27\", \"45.92\", \"22.92\", \"*\", \"33.65\", \"…\n$ H_PCT25            <chr> \"18.45\", \"41.06\", \"67.35\", \"32.21\", \"*\", \"37.64\", \"…\n$ H_MEDIAN           <chr> \"26.37\", \"61.33\", \"100.87\", \"49.26\", \"*\", \"55.5\", \"…\n$ H_PCT75            <chr> \"39.85\", \"83.45\", \"#\", \"76.63\", \"*\", \"70.61\", \"101.…\n$ H_PCT90            <chr> \"60.7\", \"110.83\", \"#\", \"105.67\", \"*\", \"98.35\", \"#\",…\n$ A_PCT10            <chr> \"31320\", \"60890\", \"95510\", \"47670\", \"21140\", \"69990…\n$ A_PCT25            <chr> \"38380\", \"85410\", \"140090\", \"66990\", \"37050\", \"7828…\n$ A_MEDIAN           <chr> \"54850\", \"127570\", \"209820\", \"102460\", \"79000\", \"11…\n$ A_PCT75            <chr> \"82890\", \"173570\", \"#\", \"159380\", \"114000\", \"146860…\n$ A_PCT90            <chr> \"126260\", \"230520\", \"#\", \"219800\", \"151910\", \"20457…\n$ ANNUAL             <lgl> NA, NA, NA, NA, TRUE, NA, NA, NA, NA, NA, NA, NA, N…\n$ HOURLY             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ `O*NET-SOC Code`   <chr> NA, NA, NA, \"11-1021\", NA, NA, NA, NA, NA, NA, NA, …\n$ `O*NET-SOC Sector` <chr> NA, NA, NA, \"Energy Efficiency\", NA, NA, NA, NA, NA…\n$ TOT_EMP_St_Paul    <dbl> 1911030, 140870, 4420, 48300, 70, 90, 7000, 7390, 9…\n$ H_MEAN_St_Paul     <dbl> 33.80, 69.10, 129.79, 59.93, NA, 59.25, 86.25, 81.1…\n$ A_MEAN_St_Paul     <dbl> 70290, 143730, 269950, 124650, 82650, 123240, 17939…\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Save the adjusted St. Paul-specific dataset to an RDS and CSV file for future analysis\nsaveRDS(st_paul_jobs_weighted, here(\"processed_data\", \"st_paul_jobs_weighted.rds\"))\nwrite_csv(st_paul_jobs_weighted, here(\"processed_data\", \"st_paul_jobs_weighted.csv\"))\n\n# Optional: Print some summary statistics for St. Paul-specific employment and wages\nsummary_st_paul_jobs <- st_paul_jobs_weighted %>%\n  summarize(\n    Total_Employment = sum(TOT_EMP_St_Paul, na.rm = TRUE),\n    Mean_Hourly_Wage = mean(H_MEAN_St_Paul, na.rm = TRUE),\n    Mean_Annual_Wage = mean(A_MEAN_St_Paul, na.rm = TRUE)\n  )\n\n# Output the summary for quick analysis\nprint(summary_st_paul_jobs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  Total_Employment Mean_Hourly_Wage Mean_Annual_Wage\n             <dbl>            <dbl>            <dbl>\n1          5751890             36.6           77675.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Replace NA values in 'O*NET-SOC Sector' with 'Other'\nst_paul_jobs_weighted <- st_paul_jobs_weighted %>%\n  mutate(`O*NET-SOC Sector` = ifelse(is.na(`O*NET-SOC Sector`), \"Other\", `O*NET-SOC Sector`))\n\n# Group by 'O*NET-SOC Sector' and calculate the total employment, mean hourly wage, and mean annual wage\nsector_summary_st_paul <- st_paul_jobs_weighted %>%\n  group_by(`O*NET-SOC Sector`) %>%\n  summarize(\n    Total_Employment = sum(TOT_EMP_St_Paul, na.rm = TRUE),\n    Mean_Hourly_Wage = mean(H_MEAN_St_Paul, na.rm = TRUE),\n    Mean_Annual_Wage = mean(A_MEAN_St_Paul, na.rm = TRUE)\n  )\n\n# Output the sector-wise summary\nprint(sector_summary_st_paul)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  `O*NET-SOC Sector`          Total_Employment Mean_Hourly_Wage Mean_Annual_Wage\n  <chr>                                  <dbl>            <dbl>            <dbl>\n1 Energy Efficiency                      66410             45.5           94669.\n2 Green Construction                    124680             37.9           78809.\n3 Other                                5537550             36.3           77193.\n4 Renewable Energy Generation            23250             44.7           92991.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Save the sector-wise summary as an RDS and CSV file for future reference\nsaveRDS(sector_summary_st_paul, here(\"processed_data\", \"sector_summary_st_paul.rds\"))\nwrite_csv(sector_summary_st_paul, here(\"processed_data\", \"sector_summary_st_paul.csv\"))\n\n# Visualization for Total Employment across sectors\nhchart(sector_summary_st_paul, \"column\", hcaes(x = `O*NET-SOC Sector`, y = Total_Employment)) %>%\n  hc_title(text = \"Total Employment by Sector in St. Paul\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Total Employment\"), labels = list(format = \"{value:,0f}\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:,0f}</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-36-1.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualization for Mean Hourly Wage across sectors\nhchart(sector_summary_st_paul, \"column\", hcaes(x = `O*NET-SOC Sector`, y = Mean_Hourly_Wage)) %>%\n  hc_title(text = \"Mean Hourly Wage by Sector in St. Paul\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Mean Hourly Wage (USD)\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:.2f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-36-2.png)\n:::\n\n```{.r .cell-code .hidden}\n# Visualization for Mean Annual Wage across sectors\nhchart(sector_summary_st_paul, \"column\", hcaes(x = `O*NET-SOC Sector`, y = Mean_Annual_Wage)) %>%\n  hc_title(text = \"Mean Annual Wage by Sector in St. Paul\") %>%\n  hc_xAxis(title = list(text = \"Sector\")) %>%\n  hc_yAxis(title = list(text = \"Mean Annual Wage (USD)\"), labels = list(format = \"{value:,0f}\")) %>%\n  hc_tooltip(pointFormat = '<b>{point.y:,0f} USD</b>')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-36-3.png)\n:::\n:::\n\n\n\n\n\n**Incorporate ACS demographics**. We will merge the OEWS data with the **ACS** data. The **ACS data** has demographic information like education, race/ethnicity, gender, and income levels. This will allow us to analyze the green job data segmented by these demographic factors in **St. Paul**.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Convert the O*NET-SOC code to character in both datasets\nst_paul_jobs_weighted <- st_paul_jobs_weighted %>%\n  mutate(`O*NET-SOC Code` = as.character(`O*NET-SOC Code`))\n\nacs_data <- acs_data %>%\n  mutate(`O*NET-SOC Code` = as.character(`O*NET-SOC Code`))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Filter the ACS data to only include rows where 'Green Job Flag' is 1\nacs_green_data <- acs_data %>% \n  filter(`Green Job Flag` == 1)\n\n# Check the filtered data to ensure it looks correct\nglimpse(acs_green_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 72\nColumns: 19\n$ RT                <chr> \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P…\n$ SERIALNO          <chr> \"2022GQ0001538\", \"2022GQ0013624\", \"2022GQ0025479\", \"…\n$ DIVISION          <dbl> 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4…\n$ SPORDER           <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 5, 1, 1, 2, 2, 2…\n$ PUMA20            <dbl> 1505, 1504, 1504, 1503, 1503, 1505, 1504, 1504, 1504…\n$ REGION            <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…\n$ ST                <dbl> 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, …\n$ AGEP              <dbl> 54, 19, 18, 50, 20, 42, 18, 18, 50, 20, 21, 67, 45, …\n$ SOCP              <chr> \"472181\", \"537062\", \"537062\", \"537062\", \"537062\", \"4…\n$ RAC1P             <chr> \"White alone\", \"Asian alone\", \"Two or More Races\", \"…\n$ SEX               <chr> \"Male\", \"Male\", \"Male\", \"Male\", \"Male\", \"Male\", \"Mal…\n$ SCHL              <chr> \"GED or alternative credential\", \"Regular high schoo…\n$ PINCP             <dbl> 0, 4000, 4000, 19200, 4000, 14700, 4000, 20000, 1920…\n$ ADJINC            <dbl> 1042311, 1042311, 1042311, 1042311, 1042311, 1042311…\n$ WAGP              <dbl> 0, 4000, 4000, 18000, 4000, 11100, 4000, 20000, 1800…\n$ PWGTP             <dbl> 1, 5, 12, 12, 8, 1, 5, 7, 12, 12, 14, 30, 35, 33, 29…\n$ `O*NET-SOC Code`  <chr> \"472181\", \"537062\", \"537062\", \"537062\", \"537062\", \"4…\n$ `O*NET-SOC Title` <chr> \"Roofers\", \"Laborers and Freight, Stock, and Materia…\n$ `Green Job Flag`  <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Remove rows with NA O*NET-SOC Codes in both datasets before merging\nst_paul_jobs_weighted <- st_paul_jobs_weighted %>%\n  filter(!is.na(`O*NET-SOC Code`))\n\nacs_green_data <- acs_green_data %>%\n  filter(!is.na(`O*NET-SOC Code`))\n\n# Re-check the unique O*NET-SOC Codes after filtering out NA values\nunique_jobs_codes <- unique(st_paul_jobs_weighted$`O*NET-SOC Code`)\nunique_acs_codes <- unique(acs_green_data$`O*NET-SOC Code`)\n\n# Find codes that exist in one dataset but not the other\nmissing_in_acs <- setdiff(unique_jobs_codes, unique_acs_codes)\nmissing_in_jobs <- setdiff(unique_acs_codes, unique_jobs_codes)\n\n# Output the results\ncat(\"Codes in jobs but not in ACS:\", missing_in_acs, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCodes in jobs but not in ACS: 11-1021 11-3071 11-9021 13-2051 17-1011 17-1012 17-2051 17-2071 17-2141 17-3011 19-3051 47-2011 47-2031 47-2051 47-2061 47-2073 47-2111 47-2131 47-2152 47-2181 47-2211 47-2221 47-4011 47-4041 49-9021 49-9051 49-9098 51-2041 51-4041 51-4121 51-8012 51-8013 51-8021 51-9012 53-6051 53-7051 53-7062 47-5041 49-9042 19-4051 51-8011 19-4041 47-5013 13-1073 47-3012 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"Codes in ACS but not in jobs:\", missing_in_jobs, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCodes in ACS but not in jobs: 472181 537062 472061 514041 111021 472111 132051 537051 172141 172051 472152 472031 474011 113071 171011 119021 518021 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Ensure the O*NET-SOC Code format is consistent\n# Remove hyphens from the codes in both datasets for consistent matching\nst_paul_jobs_weighted <- st_paul_jobs_weighted %>%\n  mutate(`O*NET-SOC Code` = gsub(\"-\", \"\", `O*NET-SOC Code`))\n\nacs_green_data <- acs_green_data %>%\n  mutate(`O*NET-SOC Code` = gsub(\"-\", \"\", `O*NET-SOC Code`))\n\n# Re-check the unique O*NET-SOC Codes after formatting\nunique_jobs_codes <- unique(st_paul_jobs_weighted$`O*NET-SOC Code`)\nunique_acs_codes <- unique(acs_green_data$`O*NET-SOC Code`)\n\n# Find codes that exist in one dataset but not the other\nmissing_in_acs <- setdiff(unique_jobs_codes, unique_acs_codes)\nmissing_in_jobs <- setdiff(unique_acs_codes, unique_jobs_codes)\n\n# Output the results\ncat(\"Codes in jobs but not in ACS:\", missing_in_acs, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCodes in jobs but not in ACS: 171012 172071 173011 193051 472011 472051 472073 472131 472211 472221 474041 499021 499051 499098 512041 514121 518012 518013 519012 536051 475041 499042 194051 518011 194041 475013 131073 473012 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"Codes in ACS but not in jobs:\", missing_in_jobs, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCodes in ACS but not in jobs:  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Merge the 'st_paul_jobs_weighted' data with 'acs_green_data' using the 'O*NET-SOC Code' column\nmerged_green_jobs_data <- st_paul_jobs_weighted %>%\n  left_join(acs_green_data, by = \"O*NET-SOC Code\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in left_join(., acs_green_data, by = \"O*NET-SOC Code\"): Detected an unexpected many-to-many relationship between `x` and `y`.\nℹ Row 1 of `x` matches multiple rows in `y`.\nℹ Row 17 of `y` matches multiple rows in `x`.\nℹ If a many-to-many relationship is expected, set `relationship =\n  \"many-to-many\"` to silence this warning.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Check the merged data to validate the merge\nglimpse(merged_green_jobs_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 124\nColumns: 55\n$ AREA               <dbl> 33460, 33460, 33460, 33460, 33460, 33460, 33460, 33…\n$ AREA_TITLE         <chr> \"Minneapolis-St. Paul-Bloomington, MN-WI\", \"Minneap…\n$ AREA_TYPE          <dbl> 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, …\n$ PRIM_STATE         <chr> \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN…\n$ NAICS              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ NAICS_TITLE        <chr> \"Cross-industry\", \"Cross-industry\", \"Cross-industry…\n$ I_GROUP            <chr> \"cross-industry\", \"cross-industry\", \"cross-industry…\n$ OWN_CODE           <dbl> 1235, 1235, 1235, 1235, 1235, 1235, 1235, 1235, 123…\n$ OCC_CODE           <chr> \"11-1021\", \"11-1021\", \"11-1021\", \"11-1021\", \"11-102…\n$ OCC_TITLE          <chr> \"General and Operations Managers\", \"General and Ope…\n$ O_GROUP            <chr> \"detailed\", \"detailed\", \"detailed\", \"detailed\", \"de…\n$ TOT_EMP            <dbl> 48300, 48300, 48300, 48300, 48300, 48300, 2610, 261…\n$ EMP_PRSE           <chr> \"2\", \"2\", \"2\", \"2\", \"2\", \"2\", \"3.1\", \"3.1\", \"3.1\", …\n$ JOBS_1000          <chr> \"25.272\", \"25.272\", \"25.272\", \"25.272\", \"25.272\", \"…\n$ LOC_QUOTIENT       <chr> \"1.09\", \"1.09\", \"1.09\", \"1.09\", \"1.09\", \"1.09\", \"1.…\n$ PCT_TOTAL          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ PCT_RPT            <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ H_MEAN             <dbl> 59.93, 59.93, 59.93, 59.93, 59.93, 59.93, 61.90, 61…\n$ A_MEAN             <dbl> 124650, 124650, 124650, 124650, 124650, 124650, 128…\n$ MEAN_PRSE          <chr> \"1.2\", \"1.2\", \"1.2\", \"1.2\", \"1.2\", \"1.2\", \"1.1\", \"1…\n$ H_PCT10            <chr> \"22.92\", \"22.92\", \"22.92\", \"22.92\", \"22.92\", \"22.92…\n$ H_PCT25            <chr> \"32.21\", \"32.21\", \"32.21\", \"32.21\", \"32.21\", \"32.21…\n$ H_MEDIAN           <chr> \"49.26\", \"49.26\", \"49.26\", \"49.26\", \"49.26\", \"49.26…\n$ H_PCT75            <chr> \"76.63\", \"76.63\", \"76.63\", \"76.63\", \"76.63\", \"76.63…\n$ H_PCT90            <chr> \"105.67\", \"105.67\", \"105.67\", \"105.67\", \"105.67\", \"…\n$ A_PCT10            <chr> \"47670\", \"47670\", \"47670\", \"47670\", \"47670\", \"47670…\n$ A_PCT25            <chr> \"66990\", \"66990\", \"66990\", \"66990\", \"66990\", \"66990…\n$ A_MEDIAN           <chr> \"102460\", \"102460\", \"102460\", \"102460\", \"102460\", \"…\n$ A_PCT75            <chr> \"159380\", \"159380\", \"159380\", \"159380\", \"159380\", \"…\n$ A_PCT90            <chr> \"219800\", \"219800\", \"219800\", \"219800\", \"219800\", \"…\n$ ANNUAL             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ HOURLY             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ `O*NET-SOC Code`   <chr> \"111021\", \"111021\", \"111021\", \"111021\", \"111021\", \"…\n$ `O*NET-SOC Sector` <chr> \"Energy Efficiency\", \"Energy Efficiency\", \"Energy E…\n$ TOT_EMP_St_Paul    <dbl> 48300, 48300, 48300, 48300, 48300, 48300, 2610, 261…\n$ H_MEAN_St_Paul     <dbl> 59.93, 59.93, 59.93, 59.93, 59.93, 59.93, 61.90, 61…\n$ A_MEAN_St_Paul     <dbl> 124650, 124650, 124650, 124650, 124650, 124650, 128…\n$ RT                 <chr> \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"…\n$ SERIALNO           <chr> \"2022HU0005354\", \"2022HU0054042\", \"2022HU0097062\", …\n$ DIVISION           <dbl> 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, …\n$ SPORDER            <dbl> 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 3, 2, 1, 1, 2, 1, 1, …\n$ PUMA20             <dbl> 1504, 1504, 1505, 1504, 1505, 1504, 1505, 1505, 150…\n$ REGION             <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …\n$ ST                 <dbl> 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,…\n$ AGEP               <dbl> 67, 35, 30, 46, 64, 37, 51, 39, 22, 34, 26, 31, 60,…\n$ SOCP               <chr> \"111021\", \"111021\", \"111021\", \"111021\", \"111021\", \"…\n$ RAC1P              <chr> \"White alone\", \"White alone\", \"Black or African Ame…\n$ SEX                <chr> \"Male\", \"Female\", \"Male\", \"Female\", \"Female\", \"Male…\n$ SCHL               <chr> \"1 or more years of college credit, no degree\", \"Ba…\n$ PINCP              <dbl> 41000, 50000, 38000, 30000, 0, 94000, 68000, 120000…\n$ ADJINC             <dbl> 1042311, 1042311, 1042311, 1042311, 1042311, 104231…\n$ WAGP               <dbl> 14000, 50000, 38000, 0, 0, 94000, 68000, 120000, 20…\n$ PWGTP              <dbl> 30, 29, 175, 25, 12, 25, 18, 35, 14, 28, 76, 27, 32…\n$ `O*NET-SOC Title`  <chr> \"General and Operations Managers\", \"General and Ope…\n$ `Green Job Flag`   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Save the merged dataset for future reference\nsaveRDS(merged_green_jobs_data, here(\"processed_data\", \"merged_green_jobs_data.rds\"))\nwrite_csv(merged_green_jobs_data, here(\"processed_data\", \"merged_green_jobs_data.csv\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Assess the number of duplicates in the merged dataset by counting occurrences of each O*NET-SOC Code\nduplication_summary <- merged_green_jobs_data %>%\n  group_by(`O*NET-SOC Code`) %>%\n  summarise(count = n()) %>%\n  arrange(desc(count))\n\n# View the summary of duplication\nprint(duplication_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 45 × 2\n   `O*NET-SOC Code` count\n   <chr>            <int>\n 1 537062              21\n 2 172141              12\n 3 472061               8\n 4 472111               7\n 5 111021               6\n 6 132051               6\n 7 172051               6\n 8 113071               3\n 9 171011               3\n10 172071               3\n# ℹ 35 more rows\n```\n\n\n:::\n:::\n\n\n\n\n\nIf we need accurate totals or averages across jobs and demographics, **aggregation** will be necessary to avoid inflating the data.\n\nIf we feel the current level of detail (with the duplicates) provides useful insights, we can keep the data as is but be mindful of how you interpret summed metrics. This is what we will do. The duplication is meaningful (for example, because a job can truly exist in multiple sectors or demographics are validly associated with multiple jobs), we choose to keep the dataset as is. This would allow us to analyze the data with all the overlaps. However, we need to be cautious that this doesn\\'t skew metrics that sum values (like total employment).\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# # Aggregate demographic and job-related data by O*NET-SOC Code and O*NET-SOC Sector after merge\n# aggregated_data <- merged_green_jobs_data %>%\n#   group_by(`O*NET-SOC Code`, `O*NET-SOC Sector`, `O*NET-SOC Title`) %>%\n#   summarise(\n#     Total_Employment = sum(TOT_EMP_St_Paul, na.rm = TRUE),\n#     Mean_Hourly_Wage = mean(H_MEAN_St_Paul, na.rm = TRUE),\n#     Mean_Annual_Wage = mean(A_MEAN_St_Paul, na.rm = TRUE),\n#     Average_Age = mean(AGEP, na.rm = TRUE),\n#     Proportion_Female = mean(SEX == \"Female\", na.rm = TRUE),\n#     Proportion_Male = mean(SEX == \"Male\", na.rm = TRUE),\n#     Average_Income = mean(PINCP, na.rm = TRUE),\n#     Proportion_White = mean(RAC1P == \"White alone\", na.rm = TRUE),\n#     Proportion_Black = mean(RAC1P == \"Black or African American alone\", na.rm = TRUE),\n#     Count = n()  # This column helps you see how many records were combined in this aggregation\n#   )\n# \n# # View the aggregated data\n# glimpse(aggregated_data)\n```\n:::\n\n\n\n\n\n**Analyze the data**. Once the datasets are merged, you can start analyzing the data to answer your research question.\n\nNow that we've merged the **OEWS** and **ACS** data, we can group by the **O\\*NET-SOC Sector** (Energy Efficiency, Renewable Energy Generation, Green Construction) and demographic factors like **education**, **race**, **gender**, and **income**.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Convert data types\nmerged_green_jobs_data <- merged_green_jobs_data %>%\n  mutate(\n    NAICS_TITLE = as.factor(NAICS_TITLE),  # Factor for industry titles\n    I_GROUP = as.factor(I_GROUP),  # Factor for industry group\n    O_GROUP = as.factor(O_GROUP),  # Factor for occupation group\n    H_PCT10 = as.numeric(H_PCT10),  # Convert percentages to numeric\n    H_PCT25 = as.numeric(H_PCT25),\n    H_MEDIAN = as.numeric(H_MEDIAN),\n    H_PCT75 = as.numeric(H_PCT75),\n    H_PCT90 = as.numeric(H_PCT90),\n    A_PCT10 = as.numeric(A_PCT10),\n    A_PCT25 = as.numeric(A_PCT25),\n    A_MEDIAN = as.numeric(A_MEDIAN),\n    A_PCT75 = as.numeric(A_PCT75),\n    A_PCT90 = as.numeric(A_PCT90),\n    ANNUAL = as.numeric(ANNUAL),  # Convert to numeric for consistency\n    HOURLY = as.numeric(HOURLY),\n    `O*NET-SOC Sector` = as.factor(`O*NET-SOC Sector`),  # Factor for green job sectors\n    TOT_EMP_St_Paul = as.numeric(TOT_EMP_St_Paul),  # Numeric for employment totals\n    H_MEAN_St_Paul = as.numeric(H_MEAN_St_Paul),  # Numeric for hourly wage in St. Paul\n    A_MEAN_St_Paul = as.numeric(A_MEAN_St_Paul),  # Numeric for annual wage in St. Paul\n    AGEP = as.factor(AGEP),  # Age as a factor if we treat it categorically\n    RAC1P = as.factor(RAC1P),  # Factor for race\n    SEX = as.factor(SEX),  # Factor for gender\n    SCHL = as.factor(SCHL),  # Factor for education level\n    PINCP = as.numeric(PINCP),  # Numeric for personal income\n    ADJINC = as.numeric(ADJINC),  # Numeric for adjusted income\n    WAGP = as.numeric(WAGP),  # Numeric for wage\n    PWGTP = as.numeric(PWGTP),  # Numeric for person weight\n    `Green Job Flag` = as.numeric(`Green Job Flag`)  # Yes/No as numeric\n  )\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: There were 10 warnings in `mutate()`.\nThe first warning was:\nℹ In argument: `H_PCT10 = as.numeric(H_PCT10)`.\nCaused by warning:\n! NAs introduced by coercion\nℹ Run `dplyr::last_dplyr_warnings()` to see the 9 remaining warnings.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Double-check the changes\nglimpse(merged_green_jobs_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 124\nColumns: 55\n$ AREA               <dbl> 33460, 33460, 33460, 33460, 33460, 33460, 33460, 33…\n$ AREA_TITLE         <chr> \"Minneapolis-St. Paul-Bloomington, MN-WI\", \"Minneap…\n$ AREA_TYPE          <dbl> 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, …\n$ PRIM_STATE         <chr> \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN\", \"MN…\n$ NAICS              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ NAICS_TITLE        <fct> Cross-industry, Cross-industry, Cross-industry, Cro…\n$ I_GROUP            <fct> cross-industry, cross-industry, cross-industry, cro…\n$ OWN_CODE           <dbl> 1235, 1235, 1235, 1235, 1235, 1235, 1235, 1235, 123…\n$ OCC_CODE           <chr> \"11-1021\", \"11-1021\", \"11-1021\", \"11-1021\", \"11-102…\n$ OCC_TITLE          <chr> \"General and Operations Managers\", \"General and Ope…\n$ O_GROUP            <fct> detailed, detailed, detailed, detailed, detailed, d…\n$ TOT_EMP            <dbl> 48300, 48300, 48300, 48300, 48300, 48300, 2610, 261…\n$ EMP_PRSE           <chr> \"2\", \"2\", \"2\", \"2\", \"2\", \"2\", \"3.1\", \"3.1\", \"3.1\", …\n$ JOBS_1000          <chr> \"25.272\", \"25.272\", \"25.272\", \"25.272\", \"25.272\", \"…\n$ LOC_QUOTIENT       <chr> \"1.09\", \"1.09\", \"1.09\", \"1.09\", \"1.09\", \"1.09\", \"1.…\n$ PCT_TOTAL          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ PCT_RPT            <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ H_MEAN             <dbl> 59.93, 59.93, 59.93, 59.93, 59.93, 59.93, 61.90, 61…\n$ A_MEAN             <dbl> 124650, 124650, 124650, 124650, 124650, 124650, 128…\n$ MEAN_PRSE          <chr> \"1.2\", \"1.2\", \"1.2\", \"1.2\", \"1.2\", \"1.2\", \"1.1\", \"1…\n$ H_PCT10            <dbl> 22.92, 22.92, 22.92, 22.92, 22.92, 22.92, 32.84, 32…\n$ H_PCT25            <dbl> 32.21, 32.21, 32.21, 32.21, 32.21, 32.21, 41.03, 41…\n$ H_MEDIAN           <dbl> 49.26, 49.26, 49.26, 49.26, 49.26, 49.26, 53.89, 53…\n$ H_PCT75            <dbl> 76.63, 76.63, 76.63, 76.63, 76.63, 76.63, 74.34, 74…\n$ H_PCT90            <dbl> 105.67, 105.67, 105.67, 105.67, 105.67, 105.67, 99.…\n$ A_PCT10            <dbl> 47670, 47670, 47670, 47670, 47670, 47670, 68310, 68…\n$ A_PCT25            <dbl> 66990, 66990, 66990, 66990, 66990, 66990, 85340, 85…\n$ A_MEDIAN           <dbl> 102460, 102460, 102460, 102460, 102460, 102460, 112…\n$ A_PCT75            <dbl> 159380, 159380, 159380, 159380, 159380, 159380, 154…\n$ A_PCT90            <dbl> 219800, 219800, 219800, 219800, 219800, 219800, 207…\n$ ANNUAL             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ HOURLY             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ `O*NET-SOC Code`   <chr> \"111021\", \"111021\", \"111021\", \"111021\", \"111021\", \"…\n$ `O*NET-SOC Sector` <fct> Energy Efficiency, Energy Efficiency, Energy Effici…\n$ TOT_EMP_St_Paul    <dbl> 48300, 48300, 48300, 48300, 48300, 48300, 2610, 261…\n$ H_MEAN_St_Paul     <dbl> 59.93, 59.93, 59.93, 59.93, 59.93, 59.93, 61.90, 61…\n$ A_MEAN_St_Paul     <dbl> 124650, 124650, 124650, 124650, 124650, 124650, 128…\n$ RT                 <chr> \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"P\", \"…\n$ SERIALNO           <chr> \"2022HU0005354\", \"2022HU0054042\", \"2022HU0097062\", …\n$ DIVISION           <dbl> 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, …\n$ SPORDER            <dbl> 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 3, 2, 1, 1, 2, 1, 1, …\n$ PUMA20             <dbl> 1504, 1504, 1505, 1504, 1505, 1504, 1505, 1505, 150…\n$ REGION             <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …\n$ ST                 <dbl> 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,…\n$ AGEP               <fct> 67, 35, 30, 46, 64, 37, 51, 39, 22, 34, 26, 31, 60,…\n$ SOCP               <chr> \"111021\", \"111021\", \"111021\", \"111021\", \"111021\", \"…\n$ RAC1P              <fct> White alone, White alone, Black or African American…\n$ SEX                <fct> Male, Female, Male, Female, Female, Male, Male, Mal…\n$ SCHL               <fct> \"1 or more years of college credit, no degree\", \"Ba…\n$ PINCP              <dbl> 41000, 50000, 38000, 30000, 0, 94000, 68000, 120000…\n$ ADJINC             <dbl> 1042311, 1042311, 1042311, 1042311, 1042311, 104231…\n$ WAGP               <dbl> 14000, 50000, 38000, 0, 0, 94000, 68000, 120000, 20…\n$ PWGTP              <dbl> 30, 29, 175, 25, 12, 25, 18, 35, 14, 28, 76, 27, 32…\n$ `O*NET-SOC Title`  <chr> \"General and Operations Managers\", \"General and Ope…\n$ `Green Job Flag`   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n```\n\n\n:::\n:::\n\n\n\n\n\nTo group by the `O*NET-SOC Sector` and demographic factors like `education`, `race`, `gender`, and `income`, we can create summary statistics for each sector to analyze how the green jobs are distributed across different demographic categories.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Group the data by sector and demographic variables, then summarize the counts and income\ngreen_job_summary <- merged_green_jobs_data %>%\n  group_by(`O*NET-SOC Sector`, SCHL, RAC1P, SEX) %>%\n  summarise(\n    total_jobs = n(),  # Count total jobs\n    mean_income = mean(PINCP, na.rm = TRUE)  # Calculate mean income for each group\n  )\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`summarise()` has grouped output by 'O*NET-SOC Sector', 'SCHL', 'RAC1P'. You\ncan override using the `.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# View the summarized data\nprint(green_job_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 52 × 6\n# Groups:   O*NET-SOC Sector, SCHL, RAC1P [46]\n   `O*NET-SOC Sector` SCHL                    RAC1P SEX   total_jobs mean_income\n   <fct>              <fct>                   <fct> <fct>      <int>       <dbl>\n 1 Energy Efficiency  1 or more years of col… Whit… Fema…          1      15000 \n 2 Energy Efficiency  1 or more years of col… Whit… Male           1      41000 \n 3 Energy Efficiency  Associate's degree      Whit… Male           1      46500 \n 4 Energy Efficiency  Bachelor's degree       Two … Fema…          1     102000 \n 5 Energy Efficiency  Bachelor's degree       Whit… Fema…          2      40000 \n 6 Energy Efficiency  Bachelor's degree       Whit… Male           3     126417.\n 7 Energy Efficiency  Grade 9                 Whit… Fema…          1          0 \n 8 Energy Efficiency  Master's degree         Asia… Male           1      80000 \n 9 Energy Efficiency  Master's degree         Whit… Fema…          1     113250 \n10 Energy Efficiency  Regular high school di… Whit… Male           1      94000 \n# ℹ 42 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Remove rows with NA in 'SCHL' or 'O*NET-SOC Sector'\ncleaned_green_job_summary <- green_job_summary %>%\n  filter(!is.na(SCHL), !is.na(`O*NET-SOC Sector`))\n\n# Bar plot for green jobs by sector and education level\nggplot(cleaned_green_job_summary, aes(x = `O*NET-SOC Sector`, y = total_jobs, fill = SCHL)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  labs(title = \"Green Jobs by Sector and Education Level\",\n       x = \"Green Job Sector\", y = \"Total Jobs\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-45-1.png)\n:::\n\n```{.r .cell-code .hidden}\n# Plot percentage of jobs by sector and education level\ngreen_job_summary_percentage <- merged_green_jobs_data %>%\n  group_by(`O*NET-SOC Sector`, SCHL) %>%\n  summarise(total_jobs = n()) %>%\n  mutate(percentage_jobs = total_jobs / sum(total_jobs) * 100)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`summarise()` has grouped output by 'O*NET-SOC Sector'. You can override using\nthe `.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nggplot(green_job_summary_percentage, aes(x = `O*NET-SOC Sector`, y = percentage_jobs, fill = SCHL)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  labs(title = \"Percentage of Green Jobs by Sector and Education Level\",\n       x = \"Green Job Sector\", y = \"Percentage of Total Jobs\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-45-2.png)\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Bar plot for green jobs by sector and race\nggplot(green_job_summary, aes(x = `O*NET-SOC Sector`, y = total_jobs, fill = RAC1P)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  labs(title = \"Green Jobs by Sector and Race\",\n       x = \"Green Job Sector\", y = \"Total Jobs\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-46-1.png)\n:::\n\n```{.r .cell-code .hidden}\n# Bar plot for green jobs by sector and race (percentage)\ngreen_job_race_percentage <- merged_green_jobs_data %>%\n  group_by(`O*NET-SOC Sector`, RAC1P) %>%\n  summarise(total_jobs = n()) %>%\n  mutate(percentage_jobs = total_jobs / sum(total_jobs) * 100)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`summarise()` has grouped output by 'O*NET-SOC Sector'. You can override using\nthe `.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nggplot(green_job_race_percentage, aes(x = `O*NET-SOC Sector`, y = percentage_jobs, fill = RAC1P)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  labs(title = \"Percentage of Green Jobs by Sector and Race\",\n       x = \"Green Job Sector\", y = \"Percentage of Total Jobs\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-46-2.png)\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Bar plot for green jobs by sector and gender\nggplot(green_job_summary, aes(x = `O*NET-SOC Sector`, y = total_jobs, fill = SEX)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  labs(title = \"Green Jobs by Sector and Gender\",\n       x = \"Green Job Sector\", y = \"Total Jobs\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-47-1.png)\n:::\n\n```{.r .cell-code .hidden}\n# Bar plot for green jobs by sector and gender (percentage)\ngreen_job_gender_percentage <- merged_green_jobs_data %>%\n  group_by(`O*NET-SOC Sector`, SEX) %>%\n  summarise(total_jobs = n()) %>%\n  mutate(percentage_jobs = total_jobs / sum(total_jobs) * 100)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`summarise()` has grouped output by 'O*NET-SOC Sector'. You can override using\nthe `.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nggplot(green_job_gender_percentage, aes(x = `O*NET-SOC Sector`, y = percentage_jobs, fill = SEX)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  labs(title = \"Percentage of Green Jobs by Sector and Gender\",\n       x = \"Green Job Sector\", y = \"Percentage of Total Jobs\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-47-2.png)\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Box plot for income distribution by sector and education level\nggplot(merged_green_jobs_data, aes(x = `O*NET-SOC Sector`, y = PINCP, fill = RAC1P)) +\n  geom_boxplot() +\n  labs(title = \"Income Distribution by Sector and Education Level\",\n       x = \"Green Job Sector\", y = \"Personal Income\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 38 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-48-1.png)\n:::\n:::\n",
    "supporting": [
      "index_files/figure-jats"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}